// The rule, driven directly. Failure case first: a guard whose rule silently stopped matching is
// a green gate over the convention it was written to enforce.

import { expect, unitTest } from '@ultimat3/testing';
import { undefinedStyleClasses } from './undefined-style-class';

const SHEETS: Readonly<Record<string, readonly string[]>> = {
  'apps/web/site/page.module.scss': ['hero', 'hero-title', 'tone-accent'],
  'apps/web/shared/shell.module.scss': ['shell'],
};
const classesOf = async (sheet: string) => SHEETS[sheet];

const page = (body: string, imports = "import styles from './page.module.scss';") => [
  { path: 'apps/web/site/page.tsx', tsx: `${imports}\n${body}\n` },
];
const check = (body: string, imports?: string) =>
  undefinedStyleClasses(page(body, imports), classesOf);

unitTest('a class the sheet does not compile is refused, with the line it is read on', async () => {
  const findings = await check('export const Page = () => <h1 class={styles.missing} />;');
  expect(findings).toHaveLength(1);
  expect(findings[0]?.code).toBe('X_UNDEFINED_STYLE_CLASS');
  expect(findings[0]?.at).toBe('apps/web/site/page.tsx:2');
  expect(findings[0]?.cause).toContain(
    'apps/web/site/page.module.scss compiles no class `missing`',
  );
  expect(findings[0]?.fix).toStartWith('add `.missing { … }` to apps/web/site/page.module.scss');
});

unitTest('a near miss is repaired with the class the sheet does declare', async () => {
  const dot = await check('export const Page = () => <h1 class={styles.heroo} />;');
  expect(dot[0]?.fix).toStartWith('styles.hero — at ');
  const bracket = await check("export const Page = () => <h1 class={styles['heroTitle']} />;");
  expect(bracket[0]?.fix).toStartWith("styles['hero-title'] — at ");
});

unitTest('a bracket read, a classList key and a second binding are all reads', async () => {
  expect(await check("export const Page = () => <h1 class={styles['nope']} />;")).toHaveLength(1);
  expect(
    await check('export const Page = () => <h1 classList={{ [styles.nope]: on() }} />;'),
  ).toHaveLength(1);
  const two =
    "import styles from './page.module.scss';\nimport shell from '../shared/shell.module.scss';";
  const findings = await check('export const Page = () => <h1 class={shell.hero} />;', two);
  expect(findings).toHaveLength(1);
  expect(findings[0]?.cause).toContain('apps/web/shared/shell.module.scss');
});

unitTest('one missing class read five times is one finding', async () => {
  const body = 'const a = [styles.gone, styles.gone, styles.gone, styles.gone, styles.gone];';
  expect(await check(body)).toHaveLength(1);
});

// The legitimate lookalikes — the reason the rule can stay switched on.
unitTest('a compiled class, however it is read, is silent', async () => {
  const silent = [
    'export const Page = () => <h1 class={styles.hero} />;',
    "export const Page = () => <h1 class={styles['hero-title']} />;",
    'export const Page = () => <h1 classList={{ [styles.hero]: on() }} />;',
    // Generated by a mixin: only the compiled sheet knows it exists.
    "export const Page = () => <h1 class={styles['tone-accent']} />;",
  ];
  for (const body of silent) expect(await check(body)).toEqual([]);
});

unitTest('a computed key, a comment and another object are out of scope', async () => {
  const silent = [
    'export const Page = (p) => <h1 class={styles[p.tone]} />;',
    `export const Page = (p) => <h1 class={styles[\`tone-\${p.tone}\`]} />;`,
    '// styles.missing\nexport const Page = () => <h1 class={styles.hero} />;',
    'export const Page = (p) => <h1 class={p.styles.missing} />;',
    'export const Page = () => <h1 class={mystyles.missing} />;',
  ];
  for (const body of silent) expect(await check(body)).toEqual([]);
});

unitTest("a sheet that does not compile is the build's finding, not this guard's", async () => {
  const imports = "import styles from './broken.module.scss';";
  expect(await check('export const Page = () => <h1 class={styles.any} />;', imports)).toEqual([]);
});
