-- GENERATED by `x db gen "init"` — do not edit.
-- Every migration is reversible or explicitly marked irreversible; `x verify` checks which.

DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS orgs;

DROP TYPE IF EXISTS theme;
DROP TYPE IF EXISTS post_status;
DROP TYPE IF EXISTS member_role;
DROP TYPE IF EXISTS billing_currency;
DROP TYPE IF EXISTS plan_code;
