-- 0002_money_scale
-- HAND-WRITTEN, as 0001 was: both predate `x db gen` in this app.
-- The statement below is byte-for-byte what `generateMigration`'s `diffTable`/`columnClause`
-- emits for this column, and the CHECK is `@ultimat3/entity`'s own `scaleCheck` — so a psql
-- session cannot write a scale the app would refuse to read back.
-- Editing an applied migration changes its checksum: X_MIGRATION_CONFLICT on the next apply.
--
-- `plans.monthly` is this app's only `money()` column, and money is three physical columns since
-- `MoneyValue.scale` began to persist: without `monthly_scale` every read of this table names a
-- column it does not have. NULL is the right value for every existing row — it means "the
-- currency's own minor unit", which is what those rows always meant. `0` would mean whole units.
--
-- The `.snapshot.json` beside this file is hand-written too, 2026-08-25, and it is what unblocked
-- the generator: `x db gen` diffs the entities against the NEWEST migration's sidecar, and with
-- none it answered X_MIGRATION_SNAPSHOT_MISSING and refused rather than emitting `create table`
-- for six tables that already exist. It did that job and is now spent — the migration AFTER this
-- one is `x db gen`'s own and carries its own sidecar, so this file is no longer the newest and
-- nothing reads the snapshot beside it. `declaredSchema` (packages/db/src/drift.ts) sorts by id
-- and returns the last one only.
--
-- What that sidecar recorded is what THIS SQL creates — `varchar(80)` where the entity declares
-- `text`, `post_slug_unique_per_org` where it declares `post_slug_unique`, and the enum types —
-- never what the entities declare. Recording the declaration would have been the lie a squash
-- tells, and the differences it made `x verify`'s `drift` step itemise were all real. They are
-- now RECORDED, by the generated migration after this one: the database is made to match the
-- entities, rather than the record rewritten to say it already did.
--
-- Two limits of the vocabulary, so a reader does not mistake them for errors: `SchemaDescription`
-- has no field for a CREATE TYPE, and one `order` per index rather than one per column, so
-- `posts_feed_idx` reads `desc` for the pair rather than for `published_at` alone. A column-level
-- CHECK was the third until `packages/db/src/check-ddl.ts` landed on 2026-08-25 — this column's
-- own scale check is now named and recorded, as `plans_monthly_scale_check`.
--
-- No `.hash` sidecar on purpose, and this is now the only migration here without one. That sidecar
-- records a hash of the WHOLE schema source, which one column does not describe; 0001 and the
-- generated migration after it each carry theirs.
--
-- The squash is still not the exit, and what it costs has SHRUNK to exactly seven. It no longer
-- loses the invariants or the column defaults — `invariant-ddl.ts` renders the checks and
-- `ColumnDescriptionLike.default` carries the declared value across the tier seam — but it still
-- loses 0001's five `CREATE TYPE … AS ENUM` and both `ALTER TABLE … REPLICA IDENTITY FULL`, which
-- nothing in the framework emits. That is 0001's `-- ungeneratable: 7` header, and
-- `migrations.test.ts` asserts the count against the statements rather than trusting it.

alter table "plans" add column "monthly_scale" integer check (monthly_scale is null or (monthly_scale >= 0 and monthly_scale <= 15));

-- down
alter table "plans" drop column "monthly_scale";
