-- 20261001221241_create_connections_and_run_events
-- GENERATED by `x db gen` from the app's entities — do not edit.
-- Editing an applied migration changes its checksum: X_MIGRATION_CONFLICT on the next apply.

create table "connections" (
  "id" uuid default gen_random_uuid() not null,
  "org_id" uuid not null,
  "label" text not null,
  "credential" text not null,
  "exit" text,
  "created_at" timestamptz default now() not null,
  primary key ("id"),
  constraint "connections_label_check" check (char_length(label) <= 80),
  constraint "connections_exit_check" check (char_length(exit) <= 200),
  constraint "connections_connection_label_present_check" check (char_length(btrim(label)) >= 1)
);
create index "connections_org_id_idx" on "connections" ("org_id");
create index "connections_org_id_created_at_idx" on "connections" ("org_id", "created_at");
create table "run_events" (
  "id" uuid default gen_random_uuid() not null,
  "org_id" uuid not null,
  "run_id" uuid not null,
  "seq" integer not null,
  "kind" text not null,
  "at" timestamptz default now() not null,
  "message" text not null,
  "prompt" integer,
  primary key ("id"),
  constraint "run_events_kind_check" check (kind in ('prompt', 'answered', 'navigated', 'extracted', 'done', 'failed')),
  constraint "run_events_message_check" check (char_length(message) <= 200),
  constraint "run_events_run_event_seq_from_one_check" check (seq >= 1)
);
create index "run_events_org_id_idx" on "run_events" ("org_id");
create index "run_events_org_id_run_id_seq_idx" on "run_events" ("org_id", "run_id", "seq");
create unique index "run_events_run_event_seq_unique_key" on "run_events" ("run_id", "seq");
alter table "connections" add constraint "connections_org_id_fkey" foreign key ("org_id") references "orgs" ("id") on delete cascade;
alter table "run_events" add constraint "run_events_org_id_fkey" foreign key ("org_id") references "orgs" ("id") on delete cascade;
alter table "run_events" replica identity full;

-- down
alter table "run_events" drop constraint "run_events_org_id_fkey";
alter table "connections" drop constraint "connections_org_id_fkey";
drop table "run_events";
drop table "connections";
