-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

alter table "credentials" add constraint "credentials_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
