-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

alter table "messages" add constraint "messages_author_id_fkey" FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE;

alter table "messages" add constraint "messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
