-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

alter table "posts" add constraint "posts_author_id_fkey" FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE;
