-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX x_admin_audit_at_idx ON public.x_admin_audit USING btree (at DESC, id DESC);

CREATE INDEX x_admin_audit_entity_idx ON public.x_admin_audit USING btree (entity, entity_id, at DESC, id DESC);
