-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX x_audit_actor_at_idx ON public.x_audit USING btree (actor_id, at DESC);

CREATE INDEX x_audit_at_idx ON public.x_audit USING btree (at DESC);
