-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX x_notify_inbox_page_idx ON public.x_notify_inbox USING btree (recipient, created_at DESC, id);

CREATE INDEX x_notify_inbox_unread_idx ON public.x_notify_inbox USING btree (recipient) WHERE (read_at IS NULL);
