-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX connections_org_id_created_at_idx ON public.connections USING btree (org_id, created_at);

CREATE INDEX connections_org_id_idx ON public.connections USING btree (org_id);
