-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX likes_member_id_idx ON public.likes USING btree (member_id);

CREATE INDEX likes_org_id_idx ON public.likes USING btree (org_id);

CREATE INDEX likes_post_id_idx ON public.likes USING btree (post_id);
