-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE UNIQUE INDEX members_member_unique_per_org_key ON public.members USING btree (org_id, user_id);

CREATE INDEX members_org_id_idx ON public.members USING btree (org_id);

CREATE INDEX members_org_id_role_idx ON public.members USING btree (org_id, role);

CREATE INDEX members_tz_8dcfa966_idx ON public.members USING btree (tz) WHERE digest_opt_in;
