-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX post_reviews_org_id_idx ON public.post_reviews USING btree (org_id);

CREATE INDEX post_reviews_org_id_reviewed_at_idx ON public.post_reviews USING btree (org_id, reviewed_at);

CREATE INDEX post_reviews_post_id_idx ON public.post_reviews USING btree (post_id);

CREATE INDEX post_reviews_reviewed_by_idx ON public.post_reviews USING btree (reviewed_by);
