-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX run_events_org_id_idx ON public.run_events USING btree (org_id);

CREATE INDEX run_events_org_id_run_id_seq_idx ON public.run_events USING btree (org_id, run_id, seq);

CREATE UNIQUE INDEX run_events_run_event_seq_unique_key ON public.run_events USING btree (run_id, seq);

CREATE INDEX run_events_run_id_idx ON public.run_events USING btree (run_id);
