-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX runs_connection_id_idx ON public.runs USING btree (connection_id);

CREATE INDEX runs_org_id_idx ON public.runs USING btree (org_id);

CREATE INDEX runs_org_id_started_at_idx ON public.runs USING btree (org_id, started_at);

CREATE INDEX runs_org_id_status_idx ON public.runs USING btree (org_id, status);
