-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX webhook_deliveries_endpoint_id_idx ON public.webhook_deliveries USING btree (endpoint_id);

CREATE INDEX webhook_deliveries_org_id_endpoint_id_at_idx ON public.webhook_deliveries USING btree (org_id, endpoint_id, at);

CREATE INDEX webhook_deliveries_org_id_idx ON public.webhook_deliveries USING btree (org_id);
