// The destructive rail's classifier: what counts, what does not, and what a keyword hiding inside
// a comment or a literal is worth (nothing). A rail with false positives is a rail authors learn
// to mark past, so the negative cases carry as much weight here as the positive ones.

import { describe, expect, test } from 'bun:test';
import {
  DESTRUCTIVE_MARKER,
  destructiveStatements,
  hasDestructiveMarker,
  isDestructive,
} from './destructive';
import { migrationDestructive } from './errors';

describe('unit · the destructive marker', () => {
  test('the marker declares the file', () => {
    expect(hasDestructiveMarker(`-- 0002_drop\n${DESTRUCTIVE_MARKER}\n\ndrop table "post";`)).toBe(
      true,
    );
  });

  test('spacing and case are not the declaration', () => {
    expect(hasDestructiveMarker('--DESTRUCTIVE:TRUE')).toBe(true);
    expect(hasDestructiveMarker('  --  destructive:   true  ')).toBe(true);
    expect(hasDestructiveMarker('-- destructive: true\r\ndrop table "post";')).toBe(true);
  });

  test('a line that merely mentions the marker has declared nothing', () => {
    expect(hasDestructiveMarker('-- destructive: true is required before a drop')).toBe(false);
    expect(hasDestructiveMarker('-- destructive: false')).toBe(false);
    expect(hasDestructiveMarker('drop table "post"; -- destructive: true')).toBe(false);
  });

  test('a file with no marker at all', () => {
    expect(hasDestructiveMarker('create table "post" ("id" uuid);')).toBe(false);
  });
});

describe('unit · destructiveStatements', () => {
  test('a dropped table', () => {
    expect(destructiveStatements('drop table "post";')).toEqual([
      { kind: 'drop-table', statement: 'drop table "post"' },
    ]);
  });

  test('a dropped column, with and without the optional keyword', () => {
    expect(destructiveStatements('alter table "post" drop column "body";')[0]?.kind).toBe(
      'drop-column',
    );
    expect(destructiveStatements('alter table "post" drop "body";')[0]?.kind).toBe('drop-column');
    expect(destructiveStatements('alter table "post" drop column if exists "body";')[0]?.kind).toBe(
      'drop-column',
    );
  });

  test('a truncate', () => {
    expect(destructiveStatements('truncate "post" cascade;')[0]?.kind).toBe('truncate');
  });

  test('a retyped column — the one `--allow-destructive` never gated', () => {
    const up = 'alter table "org" alter column "currency" type char(3) using "currency"::char(3);';
    expect(destructiveStatements(up)[0]?.kind).toBe('retype-column');
    expect(
      destructiveStatements('alter table "o" alter column "c" set data type text;')[0]?.kind,
    ).toBe('retype-column');
  });

  test('a drop that the database can rebuild is not destructive', () => {
    for (const clause of ['drop constraint "post_check"', 'drop default', 'drop not null']) {
      expect(destructiveStatements(`alter table "post" ${clause};`)).toEqual([]);
    }
    expect(destructiveStatements('drop index "post_org_id_idx";')).toEqual([]);
  });

  test('creating and adding are not destructive', () => {
    const up = [
      'create table "post" (\n  "id" uuid primary key,\n  "body" text not null\n);',
      'create unique index "post_slug_idx" on "post" ("slug");',
      'alter table "post" add column "publish_at" timestamptz;',
      'alter table "post" alter column "body" set not null;',
    ].join('\n');
    expect(destructiveStatements(up)).toEqual([]);
    expect(isDestructive(up)).toBe(false);
  });

  test('a keyword inside a comment or a literal is prose and data, not an operation', () => {
    expect(destructiveStatements('-- drop table "post"\ncreate table "post" ("id" uuid);')).toEqual(
      [],
    );
    expect(destructiveStatements('insert into "audit" values (\'drop table post\');')).toEqual([]);
    expect(destructiveStatements('/* truncate "post" */ create table "post" ("id" uuid);')).toEqual(
      [],
    );
  });

  test('the generated `-- backfill …, then: … set not null;` note is a comment, not a statement', () => {
    const up = [
      'alter table "post" add column "slug" text;',
      '-- backfill "slug", then: alter table "post" alter column "slug" set not null;',
    ].join('\n');
    expect(destructiveStatements(up)).toEqual([]);
  });

  test('every destructive statement is reported, in apply order', () => {
    const up = [
      'alter table "post" drop column "body";',
      'create index "post_org_id_idx" on "post" ("org_id");',
      'drop table "draft";',
    ].join('\n');
    expect(destructiveStatements(up).map((each) => each.kind)).toEqual([
      'drop-column',
      'drop-table',
    ]);
  });

  test('the reported statement is one line, verbatim, without the header above it', () => {
    const up = `-- 0002_drop\n-- GENERATED by \`x db gen\`\n\ndrop table\n  "post";`;
    expect(destructiveStatements(up)[0]?.statement).toBe('drop table "post"');
  });

  test('a statement past the cap is truncated rather than printed whole', () => {
    const columns = Array.from({ length: 40 }, (_, index) => `"c${index}"`).join(', ');
    const [only] = destructiveStatements(`alter table "post" drop column ${columns};`);
    expect(only?.statement.length).toBe(120);
    expect(only?.statement.endsWith('...')).toBe(true);
  });
});

describe('unit · X_MIGRATION_DESTRUCTIVE', () => {
  const first = { kind: 'drop-column', statement: 'alter table "" drop column ""' } as const;

  test('names the file, the operation and the marker that fixes it', () => {
    const error = migrationDestructive('packages/db/migrations/0002_drop.sql', first);
    expect(error.code).toBe('X_MIGRATION_DESTRUCTIVE');
    expect(error.cause).toContain('packages/db/migrations/0002_drop.sql drops a column');
    expect(error.cause).toContain(first.statement);
    expect(error.fix).toContain(DESTRUCTIVE_MARKER);
    expect(error.fix).toContain('x db gen');
  });

  test('the remaining count rides in the cause, so one finding still reads as a rewrite', () => {
    expect(migrationDestructive('m.sql', first, 3).cause).toContain('(and 3 more destructive)');
    expect(migrationDestructive('m.sql', first).cause).not.toContain('more destructive');
  });

  test('meta carries the kind and the total, for --json', () => {
    expect(migrationDestructive('m.sql', first, 2).meta).toEqual({
      file: 'm.sql',
      kind: 'drop-column',
      statements: 3,
    });
  });
});

describe('unit · the marker is a comment, not a substring', () => {
  // The rail's whole value is that an author declares a drop. A marker the scanner finds inside a
  // block comment or a dollar body is one no reviewer reading the diff would call a declaration,
  // and it bought the file past `x verify` all the same.
  test('inside a block comment it declares nothing', () => {
    expect(hasDestructiveMarker('/*\n-- destructive: true\n*/\ndrop table "post";')).toBe(false);
  });

  test('inside a dollar-quoted body it declares nothing', () => {
    expect(hasDestructiveMarker('do $fn$\n-- destructive: true\n$fn$;\ndrop table "post";')).toBe(
      false,
    );
  });

  test('inside a string literal it declares nothing', () => {
    expect(hasDestructiveMarker(`insert into "audit" values ('-- destructive: true');`)).toBe(
      false,
    );
  });

  test('a real marker after any of them still declares the file', () => {
    expect(hasDestructiveMarker('/* not it */\n-- destructive: true\ndrop table "post";')).toBe(
      true,
    );
  });
});
