// Single responsibility: what a column the DATABASE computes contributes to DDL, and what changes
// to one a migration may emit. Split from `generate.ts` because Postgres treats a generated column
// as a different thing at every step — its clause, its retype, its NOT NULL add and the way its
// expression moves are each a rule of their own, and none of them is the ordinary column's.

import { assert } from '@ultimat3/core';
import type { ColumnDescriptionLike } from './entity-shape';
import type { Plan } from './foreign-key-plan';
import type { ColumnDescription } from './introspect';

/** How a column that moved was brought back into line — what the caller has to do next, if anything. */
export type Regeneration = 'unchanged' | 'altered' | 'rebuilt';

const alterColumn = (table: string, column: string): string =>
  `alter table "${table}" alter column "${column}"`;

/**
 * The `generated always as (…) stored` clause, or `''` for every ordinary column — so a description
 * written before this field existed emits the statement it always emitted, byte for byte.
 *
 * The two rules Postgres has about the pair are refused HERE, where the entity is still named, for
 * the reason `createIndex` refuses a unique GIN in the same file: an unguarded generator writes DDL
 * whose first reader is `ROLE=migrate`, and the server's message carries none of the declaration's
 * words. A column may not be both DEFAULTED and GENERATED (`42601` — a generated column's value IS
 * its expression), and an empty expression is not one.
 */
export function generatedClause(column: ColumnDescriptionLike): string {
  const expression = column.generated;
  if (expression === undefined || expression === null) return '';
  assert(
    !column.hasDefault,
    `column "${column.column}" is declared both generated and defaulted, and Postgres has neither`,
    `drop the default from "${column.property}" — a generated column's value is its expression, computed on every write`,
  );
  assert(
    expression.trim().length > 0,
    `column "${column.column}" is generated by an empty expression`,
    `give "${column.property}" an expression, or drop the generated declaration`,
  );
  return ` generated always as (${expression}) stored`;
}

export const isGenerated = (column: ColumnDescriptionLike): boolean =>
  typeof column.generated === 'string';

/**
 * A generated column whose TYPE or whose EXPRESSION moved, brought into line without rebuilding it.
 *
 * `set expression as (…)` (Postgres 17) rewrites the table and recomputes every row, and the
 * column's indexes survive — measured. Drop-and-recreate was the alternative and is worse in two
 * ways that matter: dropping the column takes its indexes with it and nothing in this diff puts
 * them back, and `alter table … drop column` is what `destructive.ts` reads as a data loss, so
 * every expression change would have carried `-- destructive: true` on a migration that loses
 * nothing. A marker on a migration that destroys nothing is a marker reviewers learn to ignore.
 *
 * The retype carries no `using`: Postgres refuses one on a generated column outright ("column … is
 * a generated column"), which is exactly the statement `retypeColumn` emits for every other column
 * — and there is nothing to convert, because the expression produces the new type itself.
 *
 * Two transitions this cannot express, and both are refused rather than half-emitted:
 * plain → generated (there is no `set expression` for a column that has none) and a column whose
 * recorded expression is unknown. `drop expression` is the one that HAS a statement, and it is the
 * generated → plain direction, which keeps the values it computed.
 */
export function regenerate(
  table: string,
  column: ColumnDescriptionLike,
  wantedType: string,
  recorded: ColumnDescription,
  plan: Plan,
): Regeneration {
  const wanted = column.generated ?? null;
  const held = recorded.generated ?? null;
  if (wanted === null && held === null) return 'unchanged';
  // Generated -> plain: the column keeps every value it computed and simply stops being derived.
  if (wanted === null) {
    plan.up.push(`${alterColumn(table, column.column)} drop expression;`);
    plan.down.push(`${alterColumn(table, column.column)} set expression as (${held ?? ''});`);
    return 'altered';
  }
  // Plain -> generated: `set expression` needs a column that already has one, so this is the whole
  // column again. Reported as `rebuilt` so the caller can put the indexes back — an `add column`
  // implies none of them.
  if (held === null) {
    plan.up.push(
      `alter table "${table}" drop column "${column.column}";`,
      `alter table "${table}" add column "${column.column}" ${wantedType}` +
        `${generatedClause(column)}${column.notNull ? ' not null' : ''};`,
    );
    // Pushed forwards and read backwards — `down` is reversed at assembly.
    plan.down.push(
      `alter table "${table}" add column "${column.column}" ${recorded.dataType};` +
        ' -- was not a generated column',
      `alter table "${table}" drop column "${column.column}";`,
    );
    return 'rebuilt';
  }
  let moved = false;
  if (recorded.dataType !== wantedType) {
    plan.up.push(`${alterColumn(table, column.column)} type ${wantedType};`);
    plan.down.push(`${alterColumn(table, column.column)} type ${recorded.dataType};`);
    moved = true;
  }
  if (held !== wanted) {
    plan.up.push(`${alterColumn(table, column.column)} set expression as (${wanted});`);
    plan.down.push(`${alterColumn(table, column.column)} set expression as (${held});`);
    moved = true;
  }
  return moved ? 'altered' : 'unchanged';
}
