// Single responsibility: a `CatalogDescription` as files — the schema dump. Pure: the same catalog
// is the same bytes, so the gate can compare what is committed with what the migrations produce.
// It decides which file a statement belongs to; `schema-dump-table.ts` spells a table, and every
// other object is the catalog's own `pg_get_*def` text with a terminator.

import type { CatalogDescription, CatalogType } from './catalog';
import { FRAMEWORK_TABLE_PREFIX } from './drift';
import { constraintClause, createSequence, quoted, tableStatements } from './schema-dump-table';
import { literal } from './sql';

export interface SchemaDumpFile {
  /** Relative to the dump directory, POSIX: `04_tables/posts.sql`, `framework/04_tables/x_jobs.sql`. */
  readonly path: string;
  readonly content: string;
}

/** One directory per object kind, numbered in the order a database can be built in. */
export const SCHEMA_DUMP_KINDS = [
  '01_extensions',
  '02_types',
  '03_sequences',
  '04_tables',
  '05_indexes',
  '06_foreign_keys',
  '07_views',
  '08_functions',
  '09_triggers',
] as const;

export type SchemaDumpKind = (typeof SCHEMA_DUMP_KINDS)[number];

/** The framework's own tables (`x_jobs`, `x_migrations`, …) live under a twin of the same layout. */
export const FRAMEWORK_DUMP_DIR = 'framework';

/** What the dump could not spell — comments only, so it loads as nothing. */
export const UNRENDERED_DUMP_FILE = 'unrendered.sql';

/** The ceiling the `filesize` step holds for source. A longer file is split, never exempted. */
export const SCHEMA_DUMP_MAX_LINES = 500;

export const SCHEMA_DUMP_HEADER =
  '-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)';

/**
 * A name as a file name: anything outside `[A-Za-z0-9_-]` becomes `%XX` per UTF-8 byte. A `.` is
 * encoded too, which is what makes the `.<n>.sql` suffix of a split file unambiguous.
 */
export function dumpFileName(name: string): string {
  return [...new TextEncoder().encode(name)]
    .map((byte) => {
      const char = String.fromCharCode(byte);
      return /[A-Za-z0-9_-]/.test(char)
        ? char
        : `%${byte.toString(16).toUpperCase().padStart(2, '0')}`;
    })
    .join('');
}

/** The `x_` rule `appTables()` already holds: the owner (a table, else the object) decides the twin. */
const twinOf = (owner: string): string =>
  owner.startsWith(FRAMEWORK_TABLE_PREFIX) ? `${FRAMEWORK_DUMP_DIR}/` : '';

function typeStatement(type: CatalogType): string {
  if (type.kind === 'enum') {
    const labels = type.labels.map((label) => literal(label).text).join(', ');
    return `create type ${quoted(type.name)} as enum (${labels});`;
  }
  const clauses = [`create domain ${quoted(type.name)} as ${type.baseType}`];
  if (type.default !== null) clauses.push(`default ${type.default}`);
  if (type.notNull) clauses.push('not null');
  clauses.push(...type.checks.map(constraintClause));
  return `${clauses.join(' ')};`;
}

/** `pg_get_*def` text with exactly one terminator, whether or not the catalog wrote one. */
const terminated = (definition: string): string => `${definition.trim().replace(/;$/, '')};`;

const TRIGGER_STATE: ReadonlyMap<string, string> = new Map([
  ['D', 'disable trigger'],
  ['R', 'enable replica trigger'],
  ['A', 'enable always trigger'],
]);

/** Statements per file path, in insertion order within a file. */
class Buckets {
  private readonly files = new Map<string, string[]>();

  add(kind: SchemaDumpKind, owner: string, file: string, ...statements: readonly string[]): void {
    const path = `${twinOf(owner)}${kind}/${dumpFileName(file)}`;
    const bucket = this.files.get(path) ?? [];
    bucket.push(...statements);
    this.files.set(path, bucket);
  }

  entries(): readonly (readonly [string, readonly string[]])[] {
    return [...this.files.entries()];
  }
}

function collect(catalog: CatalogDescription): Buckets {
  const out = new Buckets();
  const materialized = new Set(catalog.views.filter((v) => v.materialized).map((v) => v.name));
  for (const extension of catalog.extensions) {
    const statement = `create extension if not exists ${quoted(extension.name)};`;
    out.add('01_extensions', extension.name, extension.name, statement);
  }
  for (const type of catalog.types) out.add('02_types', type.name, type.name, typeStatement(type));
  for (const sequence of catalog.sequences) {
    out.add('03_sequences', sequence.name, sequence.name, createSequence(sequence));
  }
  for (const table of catalog.tables) {
    out.add('04_tables', table.name, table.name, ...tableStatements(table));
  }
  for (const view of catalog.views) {
    const head = view.materialized ? 'create materialized view' : 'create view';
    const options = view.options === null ? '' : ` with (${view.options})`;
    const statement = `${head} ${quoted(view.name)}${options} as\n${terminated(view.definition)}`;
    out.add('07_views', view.name, view.name, statement);
  }
  for (const index of catalog.indexes) {
    // A materialized view's index rides in the view's own file: the view is built in a later
    // directory than `05_indexes`, so an index filed there would name a relation not yet created.
    const kind = materialized.has(index.table) ? '07_views' : '05_indexes';
    out.add(kind, index.table, index.table, terminated(index.definition));
  }
  for (const table of catalog.tables) {
    if (table.replicaIdentity.kind !== 'index') continue;
    const using = `replica identity using index ${quoted(table.replicaIdentity.index)}`;
    out.add('05_indexes', table.name, table.name, `alter table ${quoted(table.name)} ${using};`);
  }
  for (const key of catalog.foreignKeys) {
    const statement = `alter table ${quoted(key.table)} add ${constraintClause(key)};`;
    out.add('06_foreign_keys', key.table, key.table, statement);
  }
  for (const fn of catalog.functions) {
    out.add('08_functions', fn.name, fn.name, terminated(fn.definition));
  }
  for (const trigger of catalog.triggers) {
    const state = TRIGGER_STATE.get(trigger.enabled);
    const on = quoted(trigger.table);
    out.add('09_triggers', trigger.table, trigger.table, terminated(trigger.definition));
    if (state !== undefined) {
      const statement = `alter table ${on} ${state} ${quoted(trigger.name)};`;
      out.add('09_triggers', trigger.table, trigger.table, statement);
    }
  }
  return out;
}

/** One file, or `<name>.1.sql`, `<name>.2.sql`, … when it would pass the ceiling. */
function split(path: string, content: string): readonly SchemaDumpFile[] {
  // The trailing newline is the file's terminator, not a line of its own.
  const lines = content.replace(/\n$/, '').split('\n');
  if (lines.length <= SCHEMA_DUMP_MAX_LINES) return [{ path: `${path}.sql`, content }];
  const parts: SchemaDumpFile[] = [];
  for (let at = 0; at < lines.length; at += SCHEMA_DUMP_MAX_LINES) {
    const chunk = lines.slice(at, at + SCHEMA_DUMP_MAX_LINES).join('\n');
    parts.push({ path: `${path}.${parts.length + 1}.sql`, content: `${chunk}\n` });
  }
  return parts;
}

function unrenderedFiles(catalog: CatalogDescription): readonly SchemaDumpFile[] {
  const twins = new Map<string, string[]>();
  for (const object of catalog.unrendered) {
    const twin = twinOf(object.table ?? object.name);
    const on = object.table === null ? '' : ` on ${quoted(object.table)}`;
    const lines = twins.get(twin) ?? [];
    lines.push(`-- not rendered: ${object.kind} ${quoted(object.name)}${on}`);
    twins.set(twin, lines);
  }
  return [...twins.entries()].map(([twin, lines]) => ({
    path: `${twin}${UNRENDERED_DUMP_FILE}`,
    content: `${SCHEMA_DUMP_HEADER}\n\n${lines.join('\n')}\n`,
  }));
}

/**
 * The whole dump, sorted by path. Deterministic by construction: the catalog arrives sorted
 * (`introspectCatalog`), nothing here reads a clock, a version or an owner, and every file ends
 * in exactly one newline.
 */
export function renderSchemaDump(catalog: CatalogDescription): readonly SchemaDumpFile[] {
  const files = collect(catalog)
    .entries()
    .flatMap(([path, statements]) =>
      split(path, `${SCHEMA_DUMP_HEADER}\n\n${statements.join('\n\n')}\n`),
    );
  return [...files, ...unrenderedFiles(catalog)].sort((a, b) =>
    a.path < b.path ? -1 : a.path > b.path ? 1 : 0,
  );
}
