// The residual hole in `drift`: hand-written SQL a committed migration carries that no declaration
// and no snapshot records, so a squash discards it in silence. Two halves are proven here — the
// classification of a real, hand-written migration, and the anti-drift pair that keeps the
// generatable list equal to what `generateMigration` actually emits.

import { describe, expect, test } from 'bun:test';
import type {
  ColumnDescriptionLike,
  EntityDescriptionLike,
  IndexDescriptionLike,
} from './entity-shape';
import { generateMigration } from './generate';
import type { SchemaDescription } from './introspect';
import { stripSqlNoise } from './sql-noise';
import { statementsOf } from './statement-split';
import { GENERATABLE_FORMS, ungeneratableStatements } from './ungeneratable';

const column = (
  name: string,
  overrides: Partial<ColumnDescriptionLike> = {},
): ColumnDescriptionLike => ({
  property: name,
  column: name,
  kind: 'text',
  notNull: false,
  primaryKey: false,
  unique: false,
  hasDefault: false,
  check: null,
  references: null,
  ...overrides,
});

const index = (
  name: string,
  columns: readonly string[],
  overrides: Partial<IndexDescriptionLike> = {},
): IndexDescriptionLike => ({
  name,
  columns,
  unique: false,
  where: null,
  order: null,
  ...overrides,
});

const id = column('id', { kind: 'uuid', primaryKey: true, notNull: true });

describe('unit · a hand-written migration', () => {
  // Trimmed from `examples/dummy/packages/db/migrations/0001_init.sql`, which is hand-written and
  // is what this classifier exists for: a CREATE TYPE and a REPLICA IDENTITY reach no snapshot,
  // so a regenerated migration silently holds neither and the WAL stops carrying old row images
  // for every live query in the app.
  const up = `-- GENERATED by \`x db gen "init"\` — do not edit.
-- build: entities@6

CREATE TYPE plan_code AS ENUM ('free', 'team', 'business');

CREATE TABLE orgs (
  id    uuid PRIMARY KEY,
  slug  varchar(80) NOT NULL,
  CONSTRAINT org_slug_shape CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);
CREATE INDEX orgs_plan_code_idx ON orgs (plan_code);

-- Live queries decode the WAL for these tables.
ALTER TABLE posts REPLICA IDENTITY FULL;
ALTER TABLE likes REPLICA IDENTITY FULL;
`;

  // The separator is not part of a statement — `statementsOf` cuts on it, and the destructive
  // rail beside this one reports the same way.
  test('the three statements a regenerated migration would lose are named, not counted', () => {
    expect(ungeneratableStatements(up)).toEqual([
      "CREATE TYPE plan_code AS ENUM ('free', 'team', 'business')",
      'ALTER TABLE posts REPLICA IDENTITY FULL',
      'ALTER TABLE likes REPLICA IDENTITY FULL',
    ]);
  });

  test('a statement split across lines is judged whole and reported on one line', () => {
    // `create table` is generatable, so its absence from the report above is the assertion: a
    // classifier reading line by line calls the `CONSTRAINT …` line an unknown verb.
    expect(ungeneratableStatements(up).join(' ')).not.toContain('CONSTRAINT');
    expect(ungeneratableStatements('GRANT SELECT\n  ON posts\n  TO app;')).toEqual([
      'GRANT SELECT ON posts TO app',
    ]);
  });

  test('a chunk of comments alone is not a statement', () => {
    expect(ungeneratableStatements('-- nothing here\n/* nor here */\n')).toEqual([]);
    expect(ungeneratableStatements('')).toEqual([]);
  });

  test('a verb inside a comment or a literal is prose and data, never an operation', () => {
    // The rail that judges raw text reports both, which is how a rail earns being ignored.
    expect(
      ungeneratableStatements(
        `-- create extension pg_trgm;\ninsert into audit values ('grant select on posts');`,
      ),
    ).toEqual([`insert into audit values ('grant select on posts')`]);
  });

  test('a comment above a generated statement does not make it a finding', () => {
    // Decided on BLANKED text: the chunk `statementsOf` hands over starts with the comment, so a
    // classifier reading the raw text finds no verb it knows and reports `create table` — the
    // framework's own output, on the `-- backfill …` note `generateMigration` writes above it.
    expect(ungeneratableStatements('-- why this table\ncreate table "t" ("a" integer);')).toEqual(
      [],
    );
  });

  test('a `;` inside a literal is data, so a backfill is one finding and not two', () => {
    expect(ungeneratableStatements(`insert into t values ('a;b');`)).toEqual([
      `insert into t values ('a;b')`,
    ]);
  });

  test('the leading comments come off the excerpt, and the SQL keeps its identifiers', () => {
    expect(ungeneratableStatements('-- why\nCREATE EXTENSION "uuid-ossp";')).toEqual([
      'CREATE EXTENSION "uuid-ossp"',
    ]);
  });
});

/**
 * The two halves that keep the list and the generator together. Neither alone is enough: the first
 * says the list is not too SMALL (nothing this generator emits is reported), the second says it is
 * not too LARGE (no entry describes a statement the generator never writes). A form added here to
 * silence a false positive on hand-written SQL fails the second; a statement form added to
 * `generate.ts` and not here fails the first.
 */
describe('unit · the generatable list is the generators own output', () => {
  const before: SchemaDescription = {
    tables: [
      {
        schema: 'public',
        name: 'posts',
        columns: [
          { name: 'id', dataType: 'uuid', nullable: false, default: null, position: 1 },
          { name: 'legacy', dataType: 'text', nullable: true, default: null, position: 2 },
          { name: 'price', dataType: 'integer', nullable: true, default: null, position: 3 },
          {
            name: 'search',
            dataType: 'text',
            nullable: true,
            default: null,
            position: 4,
            generated: "coalesce(title, '')",
          },
          { name: 'plain', dataType: 'text', nullable: true, default: null, position: 5 },
        ],
        primaryKey: ['id'],
        indexes: [
          {
            name: 'posts_moved_idx',
            columns: ['id'],
            unique: false,
            primary: false,
            where: null,
            order: null,
          },
          {
            name: 'posts_gone_idx',
            columns: ['id'],
            unique: false,
            primary: false,
            where: null,
            order: null,
          },
        ],
        foreignKeys: [
          {
            name: 'posts_dropped_id_fkey',
            columns: ['id'],
            referencedTable: 'orgs',
            referencedColumns: ['id'],
            onDelete: null,
          },
        ],
        checks: [{ name: 'posts_old_rule_check', expression: 'price >= 0' }],
      },
      {
        schema: 'public',
        name: 'doomed',
        columns: [{ name: 'id', dataType: 'uuid', nullable: false, default: null, position: 1 }],
        primaryKey: ['id'],
        indexes: [],
        foreignKeys: [],
      },
    ],
  };

  const posts: EntityDescriptionLike = {
    name: 'Post',
    table: 'posts',
    primaryKey: ['id'],
    columns: [
      id,
      // A retype, so `alter column … type` is emitted.
      column('price', { kind: 'bigint' }),
      // Generated -> plain, so `drop expression` is emitted; `down` carries `set expression`.
      column('search'),
      // Plain -> generated, so the column is dropped and added again.
      column('plain', { generated: 'lower(title)' }),
      // New, so `add column` is emitted; its `references()` is an `add constraint`.
      column('org_id', { kind: 'uuid', references: 'orgs.id', onDelete: 'cascade' }),
      // NOT NULL with no default, so the `-- backfill …, then: … set not null;` note is emitted
      // above the next statement — a comment-only chunk that must be judged as no statement.
      column('title', { notNull: true }),
    ],
    indexes: [
      index('posts_moved_idx', ['id'], { unique: true }),
      index('posts_new_idx', ['org_id']),
    ],
    invariants: [
      { name: 'new_rule', kind: 'check', message: '', sql: 'price >= 1', where: null },
      {
        name: 'org_slug',
        kind: 'unique',
        message: '',
        sql: 'org_id',
        where: null,
        columns: ['org_id'],
      },
    ],
  };

  const fresh: EntityDescriptionLike = {
    name: 'Tag',
    table: 'tags',
    primaryKey: ['id'],
    columns: [id, column('label', { unique: true, notNull: true })],
    indexes: [index('tags_label_idx', ['label'], { where: 'label is not null' })],
  };

  const corpus = (): readonly string[] => {
    const migration = generateMigration({
      entities: [posts, fresh],
      current: before,
      name: 'every form',
      now: new Date('2026-01-01T00:00:00.000Z'),
      allowDestructive: true,
    });
    return [migration.up, migration.down];
  };

  test('nothing generateMigration emits is reported — a false positive on our own output', () => {
    for (const half of corpus()) expect(ungeneratableStatements(half)).toEqual([]);
  });

  test('every form on the list is a statement the corpus actually contains', () => {
    // The derivation. Without it the list is a hand-typed opinion and may quietly grow an entry
    // that excuses hand-written SQL — the exact statements this check exists to report. Read
    // through the same splitter and blanker the classifier uses, or the two would be agreeing
    // about a text neither of them judges.
    const statements = corpus()
      .flatMap((half) => statementsOf(half))
      .map((statement) => stripSqlNoise(statement).trim().toLowerCase());
    const unhit = GENERATABLE_FORMS.filter(
      (form) => !statements.some((statement) => form.pattern.test(statement)),
    ).map((form) => form.name);
    expect(unhit).toEqual([]);
  });
});
