// The generator is only trustworthy if its output is checked, so this covers both halves: the
// pure transform (upstream JSON → module text) and the 1700-odd modules actually committed —
// every one of them has to import, export the name its path promises, and survive the glyph gate.

import { describe, expect, test } from 'bun:test';
import type { IconGlyph } from '../components/icon-glyph';
import { iconElements } from '../components/icon-glyph';
import {
  GLYPHS_DIR,
  identifierFor,
  LUCIDE_VERSION,
  moduleSource,
  parseIconNodes,
} from './build-icons';

const NODES = JSON.stringify({
  search: [
    ['path', { d: 'm21 21-4.34-4.34', key: 'k1' }],
    ['circle', { cx: '11', cy: 11, r: '8', key: 'k2' }],
  ],
});

describe('parseIconNodes', () => {
  test('drops the upstream diff key and stringifies numbers', () => {
    expect(parseIconNodes(NODES).get('search')).toEqual([
      ['path', { d: 'm21 21-4.34-4.34' }],
      ['circle', { cx: '11', cy: '11', r: '8' }],
    ]);
  });

  test('refuses data the component would refuse at render time', () => {
    expect(() => parseIconNodes(JSON.stringify({ bad: [['script', {}]] }))).toThrow(/script/);
    expect(() => parseIconNodes(JSON.stringify({ empty: [] }))).toThrow(/renderable node data/);
  });

  test('a JSON array is not an icon table', () => {
    expect(() => parseIconNodes('[]')).toThrow(/icon-nodes\.json/);
  });
});

describe('identifierFor', () => {
  test('prefixes so reserved words stay legal identifiers', () => {
    expect(identifierFor('circle-alert')).toBe('iconCircleAlert');
    expect(identifierFor('delete')).toBe('iconDelete');
    expect(identifierFor('a-arrow-down')).toBe('iconAArrowDown');
  });
});

describe('moduleSource', () => {
  test('carries the generated banner, the licence line and the typed export', () => {
    const source = moduleSource('search', [['path', { d: 'M0 0' }]]);
    expect(source).toContain('GENERATED by src/icons/build-icons.ts');
    expect(source).toContain('Lucide contributors, ISC');
    expect(source).toContain("import type { IconGlyph } from '../../components/icon-glyph';");
    expect(source).toContain('export const iconSearch: IconGlyph = [');
    expect(source).toContain("['path', { d: 'M0 0' }],");
  });
});

describe('the committed glyph set', () => {
  const files = [...new Bun.Glob('*.ts').scanSync({ cwd: GLYPHS_DIR })].sort();

  test('wraps the whole upstream set, not a hand-picked corner of it', () => {
    expect(files.length).toBeGreaterThan(1500);
  });

  test('every module exports the identifier its path promises, and it is a valid glyph', async () => {
    const broken: string[] = [];
    for (const file of files) {
      const name = file.slice(0, -3);
      const module: Record<string, unknown> = await import(`${GLYPHS_DIR}${file}`);
      const glyph = module[identifierFor(name)];
      if (glyph === undefined) {
        broken.push(`${name}: no export named ${identifierFor(name)}`);
        continue;
      }
      // The namespace is `unknown`-valued on purpose: `iconElements` is what decides whether
      // what the module exported is renderable, and it throws when it is not.
      if (iconElements(glyph as IconGlyph).length === 0) broken.push(`${name}: empty glyph`);
    }
    expect(broken).toEqual([]);
  });

  test('the pinned upstream version is a real semver, so a bump is visible in the diff', () => {
    expect(LUCIDE_VERSION).toMatch(/^\d+\.\d+\.\d+$/);
  });
});
