-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX blocks_blocked_id_idx ON public.blocks USING btree (blocked_id);

CREATE INDEX blocks_blocker_id_idx ON public.blocks USING btree (blocker_id);
