-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX comments_author_id_idx ON public.comments USING btree (author_id);

CREATE INDEX comments_post_id_created_at_id_idx ON public.comments USING btree (post_id, created_at, id);

CREATE INDEX comments_post_id_idx ON public.comments USING btree (post_id);
