-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX friendships_addressee_id_idx ON public.friendships USING btree (addressee_id);

CREATE INDEX friendships_addressee_id_status_idx ON public.friendships USING btree (addressee_id, status);

CREATE INDEX friendships_requester_id_idx ON public.friendships USING btree (requester_id);
