-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX notifications_actor_id_idx ON public.notifications USING btree (actor_id);

CREATE INDEX notifications_user_id_created_at_08493ec4_idx ON public.notifications USING btree (user_id DESC, created_at DESC);

CREATE INDEX notifications_user_id_created_at_idx ON public.notifications USING btree (user_id DESC, created_at DESC);

CREATE INDEX notifications_user_id_idx ON public.notifications USING btree (user_id);
