-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX posts_author_id_idx ON public.posts USING btree (author_id);

CREATE INDEX posts_author_id_published_at_08493ec4_idx ON public.posts USING btree (author_id DESC, published_at DESC);

CREATE INDEX posts_author_id_published_at_idx ON public.posts USING btree (author_id DESC, published_at DESC);

CREATE INDEX posts_published_at_1d8a8b38_idx ON public.posts USING btree (published_at DESC) WHERE (audience = 'public'::text);

CREATE INDEX posts_published_at_idx ON public.posts USING btree (published_at DESC) WHERE (audience = 'public'::text);
