-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX sessions_expires_at_idx ON public.sessions USING btree (expires_at);

CREATE INDEX sessions_user_id_idx ON public.sessions USING btree (user_id);
