-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX users_created_at_08493ec4_idx ON public.users USING btree (created_at DESC);

CREATE INDEX users_created_at_idx ON public.users USING btree (created_at DESC);
