-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_api_keys" (
  "id" text not null,
  "prefix" text not null,
  "key_hash" text not null,
  "user_id" uuid,
  "org_id" uuid,
  "scopes" text[] default '{}'::text[] not null,
  "last_used_at" timestamp with time zone,
  "expires_at" timestamp with time zone,
  "revoked_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  constraint "x_api_keys_pkey" PRIMARY KEY (id),
  constraint "x_api_keys_prefix_key" UNIQUE (prefix)
);
