-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_job_counters" (
  "job" text not null,
  "bucket_ms" integer not null,
  "bucket_start" timestamp with time zone not null,
  "done" bigint default 0 not null,
  "retried" bigint default 0 not null,
  "failed" bigint default 0 not null,
  "dead" bigint default 0 not null,
  "duration_ms" bigint default 0 not null,
  constraint "x_job_counters_pkey" PRIMARY KEY (job, bucket_ms, bucket_start)
);
