-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_job_leases" (
  "lease_key" text not null,
  "slot" integer not null,
  "holder" text not null,
  "expires_at" timestamp with time zone not null,
  constraint "x_job_leases_pkey" PRIMARY KEY (lease_key, slot)
);
