-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_mcp_confirmations" (
  "id" uuid not null,
  "actor_id" text not null,
  "org_id" text,
  "tool" text not null,
  "input_digest" text not null,
  "sealed_arguments" text not null,
  "status" text default 'pending'::text not null,
  "created_at" timestamp with time zone not null,
  "expires_at" timestamp with time zone not null,
  "decided_at" timestamp with time zone,
  "decided_by" text,
  "consumed_at" timestamp with time zone,
  constraint "x_mcp_confirmations_pkey" PRIMARY KEY (id)
);
