-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_notify_digests" (
  "seq" bigint generated always as identity (sequence name "x_notify_digests_seq_seq" start with 1 increment by 1 minvalue 1 maxvalue 9223372036854775807 cache 1 no cycle) not null,
  "recipient" text not null,
  "notifier" text not null,
  "channel" text not null,
  "group_key" text not null,
  "ends_at" timestamp with time zone not null,
  "sealed" boolean default false not null,
  "events" jsonb not null,
  "appended_by" text[] default '{}'::text[] not null,
  constraint "x_notify_digests_pkey" PRIMARY KEY (seq)
);
