-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_outbox" (
  "id" uuid not null,
  "job" text not null,
  "queue" text default 'default'::text not null,
  "input" jsonb not null,
  "idempotency_key" text not null,
  "max_attempts" integer default 3 not null,
  "run_at" timestamp with time zone default now() not null,
  "staged_at" timestamp with time zone default now() not null,
  "tenant_id" text,
  "traceparent" text,
  "enqueued_by" text,
  "published_at" timestamp with time zone,
  "claimed_at" timestamp with time zone,
  "claimed_by" text,
  "run_id" uuid default gen_random_uuid() not null,
  constraint "x_outbox_pkey" PRIMARY KEY (id)
);
