-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_scheduler_state" (
  "task_name" text not null,
  "last_fired_at" timestamp with time zone not null,
  "updated_at" timestamp with time zone default now() not null,
  "fired_occurrence_at" timestamp with time zone,
  "fired_at" timestamp with time zone,
  constraint "x_scheduler_state_pkey" PRIMARY KEY (task_name)
);
