-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_verifications" (
  "id" text not null,
  "purpose" text not null,
  "identifier" text not null,
  "token_hash" text not null,
  "expires_at" timestamp with time zone not null,
  "consumed_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  constraint "x_verifications_pkey" PRIMARY KEY (id),
  constraint "x_verifications_purpose_identifier_key" UNIQUE (purpose, identifier)
);
