-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX x_jobs_claim_idx ON public.x_jobs USING btree (queue, run_at) WHERE (state = ANY (ARRAY['ready'::text, 'delayed'::text, 'suspended'::text]));

CREATE INDEX x_jobs_created_idx ON public.x_jobs USING btree (created_at DESC, id DESC);

CREATE UNIQUE INDEX x_jobs_name_tenant_idempotency_live_idx ON public.x_jobs USING btree (name, COALESCE(tenant_id, ''::text), idempotency_key) WHERE (state = ANY (ARRAY['ready'::text, 'delayed'::text, 'running'::text, 'suspended'::text]));
