-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

CREATE INDEX x_notify_digests_ends_idx ON public.x_notify_digests USING btree (ends_at);

CREATE UNIQUE INDEX x_notify_digests_open_idx ON public.x_notify_digests USING btree (recipient, notifier, channel, group_key) WHERE (NOT sealed);

CREATE INDEX x_notify_digests_slot_idx ON public.x_notify_digests USING btree (recipient, notifier, channel, group_key, ends_at);
