// The root `.gitattributes` `x new` writes: every text file LF in the index and the checkout, every
// binary type left byte-for-byte. The framework repo's own root file opens with the same block —
// `scaffold-gitattributes.test.ts` refuses the two drifting apart.

/** The path, relative to the app root — git reads attributes from here for the whole tree. */
export const ROOT_GITATTRIBUTES_PATH = '.gitattributes';

/**
 * Binary types an app or the framework plausibly tracks: images, icons, fonts, WebAssembly and the
 * archives fixtures arrive in. `text=auto` would usually detect them, but "usually" is a heuristic
 * over the first 8000 bytes — `binary` is the statement, and it also stops a textual diff.
 */
export const BINARY_EXTENSIONS: readonly string[] = [
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'avif',
  'ico',
  'woff',
  'woff2',
  'ttf',
  'otf',
  'wasm',
  'pdf',
  'zip',
  'gz',
  'tgz',
  'tar',
];

/**
 * `* text=auto eol=lf` is not cosmetic. Git for Windows installs with `core.autocrlf=true`, so a
 * checkout without it rewrites every file to CRLF: Biome (`lineEnding: "lf"`) then flags every
 * file, every `split('\n')` scanner sees a trailing `\r`, and every byte-compared artifact — the
 * manifest, the schema dump, a migration's checksum — reads as drift on a correct tree. Pinned
 * here, it holds for every clone whatever the contributor's git config says.
 */
export const LINE_ENDING_ATTRIBUTES = `# Every text file is LF, in the index and in the checkout, whatever \`core.autocrlf\` says. Git for
# Windows defaults it to true: without this line a Windows clone is CRLF, Biome flags every file and
# every byte-compared artifact (manifest, schema dump, migration checksum) reads as drift.
* text=auto eol=lf

# Binary, stated rather than detected: never line-ending converted, never textually diffed.
${BINARY_EXTENSIONS.map((extension) => `*.${extension} binary`).join('\n')}
`;

/** The app's root file: the shared block, then the app's one generated file git should collapse. */
export const rootGitattributes = (): string => `${LINE_ENDING_ATTRIBUTES}
# Bun's lockfile. Regenerated by \`bun install\`, never edited by hand.
bun.lock -diff linguist-generated=true
`;

/** The file `x new` writes at the app root — one entry in `repoFiles`' list. */
export const rootGitattributesFile = (): { readonly path: string; readonly contents: string } => ({
  path: ROOT_GITATTRIBUTES_PATH,
  contents: rootGitattributes(),
});
