// The Lucide "ad" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAd: IconGlyph = [
  ['path', { d: 'M10 13H6' }],
  ['path', { d: 'M10 15v-4a2 2 0 0 0-4 0v4' }],
  [
    'path',
    {
      d: 'M14 14.5a.5.5 0 0 0 .5.5h1a2.5 2.5 0 0 0 2.5-2.5v-1A2.5 2.5 0 0 0 15.5 9h-1a.5.5 0 0 0-.5.5z',
    },
  ],
  ['rect', { x: '2', y: '5', width: '20', height: '14', rx: '2' }],
];
