// The Lucide "align-vertical-justify-start" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAlignVerticalJustifyStart: IconGlyph = [
  ['rect', { width: '14', height: '6', x: '5', y: '16', rx: '2' }],
  ['rect', { width: '10', height: '6', x: '7', y: '6', rx: '2' }],
  ['path', { d: 'M2 2h20' }],
];
