// The Lucide "align-end-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAlignEndHorizontal: IconGlyph = [
  ['rect', { width: '6', height: '16', x: '4', y: '2', rx: '2' }],
  ['rect', { width: '6', height: '9', x: '14', y: '9', rx: '2' }],
  ['path', { d: 'M22 22H2' }],
];
