// The Lucide "align-vertical-space-around" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAlignVerticalSpaceAround: IconGlyph = [
  ['rect', { width: '10', height: '6', x: '7', y: '9', rx: '2' }],
  ['path', { d: 'M22 20H2' }],
  ['path', { d: 'M22 4H2' }],
];
