// The Lucide "align-vertical-distribute-center" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAlignVerticalDistributeCenter: IconGlyph = [
  ['path', { d: 'M22 17h-3' }],
  ['path', { d: 'M22 7h-5' }],
  ['path', { d: 'M5 17H2' }],
  ['path', { d: 'M7 7H2' }],
  ['rect', { x: '5', y: '14', width: '14', height: '6', rx: '2' }],
  ['rect', { x: '7', y: '4', width: '10', height: '6', rx: '2' }],
];
