// The Lucide "align-horizontal-space-between" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAlignHorizontalSpaceBetween: IconGlyph = [
  ['rect', { width: '6', height: '14', x: '3', y: '5', rx: '2' }],
  ['rect', { width: '6', height: '10', x: '15', y: '7', rx: '2' }],
  ['path', { d: 'M3 2v20' }],
  ['path', { d: 'M21 2v20' }],
];
