// The Lucide "antenna" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAntenna: IconGlyph = [
  ['path', { d: 'M2 12 7 2' }],
  ['path', { d: 'm7 12 5-10' }],
  ['path', { d: 'm12 12 5-10' }],
  ['path', { d: 'm17 12 5-10' }],
  ['path', { d: 'M4.5 7h15' }],
  ['path', { d: 'M12 16v6' }],
];
