// The Lucide "app-window-mac" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAppWindowMac: IconGlyph = [
  ['rect', { width: '20', height: '16', x: '2', y: '4', rx: '2' }],
  ['path', { d: 'M6 8h.01' }],
  ['path', { d: 'M10 8h.01' }],
  ['path', { d: 'M14 8h.01' }],
];
