// The Lucide "arrow-down-to-dot" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowDownToDot: IconGlyph = [
  ['path', { d: 'M12 2v14' }],
  ['path', { d: 'm19 9-7 7-7-7' }],
  ['circle', { cx: '12', cy: '21', r: '1' }],
];
