// The Lucide "arrow-left-to-line" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowLeftToLine: IconGlyph = [
  ['path', { d: 'M3 19V5' }],
  ['path', { d: 'm13 6-6 6 6 6' }],
  ['path', { d: 'M7 12h14' }],
];
