// The Lucide "arrow-down-a-z" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowDownAZ: IconGlyph = [
  ['path', { d: 'm3 16 4 4 4-4' }],
  ['path', { d: 'M7 20V4' }],
  ['path', { d: 'M20 8h-5' }],
  ['path', { d: 'M15 10V6.5a2.5 2.5 0 0 1 5 0V10' }],
  ['path', { d: 'M15 14h5l-5 6h5' }],
];
