// The Lucide "arrow-up-from-dot" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowUpFromDot: IconGlyph = [
  ['path', { d: 'm5 9 7-7 7 7' }],
  ['path', { d: 'M12 16V2' }],
  ['circle', { cx: '12', cy: '21', r: '1' }],
];
