// The Lucide "arrow-up-to-line" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowUpToLine: IconGlyph = [
  ['path', { d: 'M5 3h14' }],
  ['path', { d: 'm18 13-6-6-6 6' }],
  ['path', { d: 'M12 7v14' }],
];
