// The Lucide "arrows-up-from-line" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowsUpFromLine: IconGlyph = [
  ['path', { d: 'm4 6 3-3 3 3' }],
  ['path', { d: 'M7 17V3' }],
  ['path', { d: 'm14 6 3-3 3 3' }],
  ['path', { d: 'M17 17V3' }],
  ['path', { d: 'M4 21h16' }],
];
