// The Lucide "arrow-down-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowDownRight: IconGlyph = [
  ['path', { d: 'm7 7 10 10' }],
  ['path', { d: 'M17 7v10H7' }],
];
