// The Lucide "arrow-right-to-line" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowRightToLine: IconGlyph = [
  ['path', { d: 'M17 12H3' }],
  ['path', { d: 'm11 18 6-6-6-6' }],
  ['path', { d: 'M21 5v14' }],
];
