// The Lucide "arrow-up-wide-narrow" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowUpWideNarrow: IconGlyph = [
  ['path', { d: 'm3 8 4-4 4 4' }],
  ['path', { d: 'M7 4v16' }],
  ['path', { d: 'M11 12h10' }],
  ['path', { d: 'M11 16h7' }],
  ['path', { d: 'M11 20h4' }],
];
