// The Lucide "arrow-up-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowUpLeft: IconGlyph = [
  ['path', { d: 'M7 17V7h10' }],
  ['path', { d: 'M17 17 7 7' }],
];
