// The Lucide "arrow-down-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowDownLeft: IconGlyph = [
  ['path', { d: 'M17 7 7 17' }],
  ['path', { d: 'M17 17H7V7' }],
];
