// The Lucide "arrow-down-to-line" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowDownToLine: IconGlyph = [
  ['path', { d: 'M12 17V3' }],
  ['path', { d: 'm6 11 6 6 6-6' }],
  ['path', { d: 'M19 21H5' }],
];
