// The Lucide "arrow-right-from-line" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconArrowRightFromLine: IconGlyph = [
  ['path', { d: 'M3 5v14' }],
  ['path', { d: 'M21 12H7' }],
  ['path', { d: 'm15 18 6-6-6-6' }],
];
