// The Lucide "asterisk" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAsterisk: IconGlyph = [
  ['path', { d: 'M12 6v12' }],
  ['path', { d: 'M17.196 9 6.804 15' }],
  ['path', { d: 'm6.804 9 10.392 6' }],
];
