// The Lucide "audio-lines" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconAudioLines: IconGlyph = [
  ['path', { d: 'M2 10v3' }],
  ['path', { d: 'M6 6v11' }],
  ['path', { d: 'M10 3v18' }],
  ['path', { d: 'M14 8v7' }],
  ['path', { d: 'M18 5v13' }],
  ['path', { d: 'M22 10v3' }],
];
