// The Lucide "banknote" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBanknote: IconGlyph = [
  ['rect', { width: '20', height: '12', x: '2', y: '6', rx: '2' }],
  ['circle', { cx: '12', cy: '12', r: '2' }],
  ['path', { d: 'M6 12h.01M18 12h.01' }],
];
