// The Lucide "barcode" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBarcode: IconGlyph = [
  ['path', { d: 'M3 5v14' }],
  ['path', { d: 'M8 5v14' }],
  ['path', { d: 'M12 5v14' }],
  ['path', { d: 'M17 5v14' }],
  ['path', { d: 'M21 5v14' }],
];
