// The Lucide "battery-medium" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBatteryMedium: IconGlyph = [
  ['path', { d: 'M10 14v-4' }],
  ['path', { d: 'M22 14v-4' }],
  ['path', { d: 'M6 14v-4' }],
  ['rect', { x: '2', y: '6', width: '16', height: '12', rx: '2' }],
];
