// The Lucide "battery" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBattery: IconGlyph = [
  ['path', { d: 'M 22 14 L 22 10' }],
  ['rect', { x: '2', y: '6', width: '16', height: '12', rx: '2' }],
];
