// The Lucide "bed" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBed: IconGlyph = [
  ['path', { d: 'M2 4v16' }],
  ['path', { d: 'M2 8h18a2 2 0 0 1 2 2v10' }],
  ['path', { d: 'M2 17h20' }],
  ['path', { d: 'M6 8v9' }],
];
