// The Lucide "between-vertical-start" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBetweenVerticalStart: IconGlyph = [
  ['rect', { width: '7', height: '13', x: '3', y: '8', rx: '1' }],
  ['path', { d: 'm15 2-3 3-3-3' }],
  ['rect', { width: '7', height: '13', x: '14', y: '8', rx: '1' }],
];
