// The Lucide "between-horizontal-start" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBetweenHorizontalStart: IconGlyph = [
  ['rect', { width: '13', height: '7', x: '8', y: '3', rx: '1' }],
  ['path', { d: 'm2 9 3 3-3 3' }],
  ['rect', { width: '13', height: '7', x: '8', y: '14', rx: '1' }],
];
