// The Lucide "binary" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBinary: IconGlyph = [
  ['rect', { x: '14', y: '14', width: '4', height: '6', rx: '2' }],
  ['rect', { x: '6', y: '4', width: '4', height: '6', rx: '2' }],
  ['path', { d: 'M6 20h4' }],
  ['path', { d: 'M14 10h4' }],
  ['path', { d: 'M6 14h2v6' }],
  ['path', { d: 'M14 4h2v6' }],
];
