// The Lucide "bluetooth-connected" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBluetoothConnected: IconGlyph = [
  ['path', { d: 'm7 7 10 10-5 5V2l5 5L7 17' }],
  ['line', { x1: '18', x2: '21', y1: '12', y2: '12' }],
  ['line', { x1: '3', x2: '6', y1: '12', y2: '12' }],
];
