// The Lucide "bluetooth" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBluetooth: IconGlyph = [['path', { d: 'm7 7 10 10-5 5V2l5 5L7 17' }]];
