// The Lucide "bluetooth-off" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconBluetoothOff: IconGlyph = [
  ['path', { d: 'm17 17-5 5V12l-5 5' }],
  ['path', { d: 'm2 2 20 20' }],
  ['path', { d: 'M14.5 9.5 17 7l-5-5v4.5' }],
];
