// The Lucide "calendar-fold" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCalendarFold: IconGlyph = [
  ['path', { d: 'M16 2v3' }],
  [
    'path',
    {
      d: 'M21 15V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h10v-5a1 1 0 011-1za2.4 2.4 0 01-.706 1.706l-3.588 3.588A2.4 2.4 0 0115 21',
    },
  ],
  ['path', { d: 'M3 9h18' }],
  ['path', { d: 'M8 2v3' }],
];
