// The Lucide "calendar-search" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCalendarSearch: IconGlyph = [
  ['path', { d: 'M16 2v3' }],
  ['path', { d: 'M21 10.69V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h7.25' }],
  ['path', { d: 'm22 21-1.875-1.875' }],
  ['path', { d: 'M3 9h18' }],
  ['path', { d: 'M8 2v3' }],
  ['circle', { cx: '18', cy: '17', r: '3' }],
];
