// The Lucide "calendar-x-2" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCalendarX2: IconGlyph = [
  ['path', { d: 'M16 2v3' }],
  ['path', { d: 'm17 16 5 5' }],
  ['path', { d: 'm17 21 5-5' }],
  ['path', { d: 'M21 12V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h8' }],
  ['path', { d: 'M3 9h18' }],
  ['path', { d: 'M8 2v3' }],
];
