// The Lucide "captions" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCaptions: IconGlyph = [
  ['rect', { width: '18', height: '14', x: '3', y: '5', rx: '2', ry: '2' }],
  ['path', { d: 'M7 15h4M15 15h2M7 11h2M13 11h4' }],
];
