// The Lucide "case-lower" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCaseLower: IconGlyph = [
  ['path', { d: 'M10 9v7' }],
  ['path', { d: 'M14 6v10' }],
  ['circle', { cx: '17.5', cy: '12.5', r: '3.5' }],
  ['circle', { cx: '6.5', cy: '12.5', r: '3.5' }],
];
