// The Lucide "chart-no-axes-gantt" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartNoAxesGantt: IconGlyph = [
  ['path', { d: 'M6 5h12' }],
  ['path', { d: 'M4 12h10' }],
  ['path', { d: 'M12 19h8' }],
];
