// The Lucide "chart-bar-stacked" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartBarStacked: IconGlyph = [
  ['path', { d: 'M11 13v4' }],
  ['path', { d: 'M15 5v4' }],
  ['path', { d: 'M3 3v16a2 2 0 0 0 2 2h16' }],
  ['rect', { x: '7', y: '13', width: '9', height: '4', rx: '1' }],
  ['rect', { x: '7', y: '5', width: '12', height: '4', rx: '1' }],
];
