// The Lucide "chart-column" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartColumn: IconGlyph = [
  ['path', { d: 'M3 3v16a2 2 0 0 0 2 2h16' }],
  ['path', { d: 'M18 17V9' }],
  ['path', { d: 'M13 17V5' }],
  ['path', { d: 'M8 17v-3' }],
];
