// The Lucide "chart-gantt" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartGantt: IconGlyph = [
  ['path', { d: 'M10 6h8' }],
  ['path', { d: 'M12 16h6' }],
  ['path', { d: 'M3 3v16a2 2 0 0 0 2 2h16' }],
  ['path', { d: 'M8 11h7' }],
];
