// The Lucide "chart-column-big" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartColumnBig: IconGlyph = [
  ['path', { d: 'M3 3v16a2 2 0 0 0 2 2h16' }],
  ['rect', { x: '15', y: '5', width: '4', height: '12', rx: '1' }],
  ['rect', { x: '7', y: '8', width: '4', height: '9', rx: '1' }],
];
