// The Lucide "chart-bar-decreasing" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartBarDecreasing: IconGlyph = [
  ['path', { d: 'M3 3v16a2 2 0 0 0 2 2h16' }],
  ['path', { d: 'M7 11h8' }],
  ['path', { d: 'M7 16h3' }],
  ['path', { d: 'M7 6h12' }],
];
