// The Lucide "chart-no-axes-column" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartNoAxesColumn: IconGlyph = [
  ['path', { d: 'M5 21v-6' }],
  ['path', { d: 'M12 21V3' }],
  ['path', { d: 'M19 21V9' }],
];
