// The Lucide "chart-column-decreasing" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChartColumnDecreasing: IconGlyph = [
  ['path', { d: 'M13 17V9' }],
  ['path', { d: 'M18 17v-3' }],
  ['path', { d: 'M3 3v16a2 2 0 0 0 2 2h16' }],
  ['path', { d: 'M8 17V5' }],
];
