// The Lucide "check-line" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCheckLine: IconGlyph = [
  ['path', { d: 'M20 4L9 15' }],
  ['path', { d: 'M21 19L3 19' }],
  ['path', { d: 'M9 15L4 10' }],
];
