// The Lucide "check" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCheck: IconGlyph = [['path', { d: 'M20 6 9 17l-5-5' }]];
