// The Lucide "chevrons-up-down" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronsUpDown: IconGlyph = [
  ['path', { d: 'm7 15 5 5 5-5' }],
  ['path', { d: 'm7 9 5-5 5 5' }],
];
