// The Lucide "chevron-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronUp: IconGlyph = [['path', { d: 'm18 15-6-6-6 6' }]];
