// The Lucide "chevrons-left-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronsLeftRight: IconGlyph = [
  ['path', { d: 'm9 7-5 5 5 5' }],
  ['path', { d: 'm15 7 5 5-5 5' }],
];
