// The Lucide "chevrons-down-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronsDownUp: IconGlyph = [
  ['path', { d: 'm7 20 5-5 5 5' }],
  ['path', { d: 'm7 4 5 5 5-5' }],
];
