// The Lucide "chevron-last" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronLast: IconGlyph = [
  ['path', { d: 'm7 18 6-6-6-6' }],
  ['path', { d: 'M17 6v12' }],
];
