// The Lucide "chevrons-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronsRight: IconGlyph = [
  ['path', { d: 'm6 17 5-5-5-5' }],
  ['path', { d: 'm13 17 5-5-5-5' }],
];
