// The Lucide "chevrons-right-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronsRightLeft: IconGlyph = [
  ['path', { d: 'm20 17-5-5 5-5' }],
  ['path', { d: 'm4 17 5-5-5-5' }],
];
