// The Lucide "chevron-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronLeft: IconGlyph = [['path', { d: 'm15 18-6-6 6-6' }]];
