// The Lucide "chevrons-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronsLeft: IconGlyph = [
  ['path', { d: 'm11 17-5-5 5-5' }],
  ['path', { d: 'm18 17-5-5 5-5' }],
];
