// The Lucide "chevron-first" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronFirst: IconGlyph = [
  ['path', { d: 'm17 18-6-6 6-6' }],
  ['path', { d: 'M7 6v12' }],
];
