// The Lucide "chevrons-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconChevronsUp: IconGlyph = [
  ['path', { d: 'm17 11-5-5-5 5' }],
  ['path', { d: 'm17 18-5-5-5 5' }],
];
