// The Lucide "circle-ellipsis" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleEllipsis: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '10' }],
  ['path', { d: 'M17 12h.01' }],
  ['path', { d: 'M12 12h.01' }],
  ['path', { d: 'M7 12h.01' }],
];
