// The Lucide "circle-arrow-out-down-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleArrowOutDownRight: IconGlyph = [
  ['path', { d: 'M12 22a10 10 0 1 1 10-10' }],
  ['path', { d: 'M22 22 12 12' }],
  ['path', { d: 'M22 16v6h-6' }],
];
