// The Lucide "circle-pile" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCirclePile: IconGlyph = [
  ['circle', { cx: '12', cy: '19', r: '2' }],
  ['circle', { cx: '12', cy: '5', r: '2' }],
  ['circle', { cx: '16', cy: '12', r: '2' }],
  ['circle', { cx: '20', cy: '19', r: '2' }],
  ['circle', { cx: '4', cy: '19', r: '2' }],
  ['circle', { cx: '8', cy: '12', r: '2' }],
];
