// The Lucide "circle-equal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleEqual: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '10' }],
  ['path', { d: 'M7 10h10' }],
  ['path', { d: 'M7 14h10' }],
];
