// The Lucide "circle-slash" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleSlash: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '10' }],
  ['line', { x1: '9', x2: '15', y1: '15', y2: '9' }],
];
