// The Lucide "circle-arrow-out-down-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleArrowOutDownLeft: IconGlyph = [
  ['path', { d: 'M2 12a10 10 0 1 1 10 10' }],
  ['path', { d: 'm2 22 10-10' }],
  ['path', { d: 'M8 22H2v-6' }],
];
