// The Lucide "circle-stop" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleStop: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '10' }],
  ['rect', { x: '9', y: '9', width: '6', height: '6', rx: '1' }],
];
