// The Lucide "circle-small" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleSmall: IconGlyph = [['circle', { cx: '12', cy: '12', r: '6' }]];
