// The Lucide "circle-arrow-out-up-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleArrowOutUpLeft: IconGlyph = [
  ['path', { d: 'M2 8V2h6' }],
  ['path', { d: 'm2 2 10 10' }],
  ['path', { d: 'M12 2A10 10 0 1 1 2 12' }],
];
