// The Lucide "circle-user-round" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleUserRound: IconGlyph = [
  ['path', { d: 'M17.925 20.056a6 6 0 0 0-11.851.001' }],
  ['circle', { cx: '12', cy: '11', r: '4' }],
  ['circle', { cx: '12', cy: '12', r: '10' }],
];
