// The Lucide "circle-gauge" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCircleGauge: IconGlyph = [
  ['path', { d: 'M15.6 2.7a10 10 0 1 0 5.7 5.7' }],
  ['circle', { cx: '12', cy: '12', r: '2' }],
  ['path', { d: 'M13.4 10.6 19 5' }],
];
