// The Lucide "clock-arrow-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconClockArrowRight: IconGlyph = [
  ['path', { d: 'M12 6v6l2 1' }],
  ['path', { d: 'M13.5 21.885A10 10 0 1 1 22 12' }],
  ['path', { d: 'M14 18h8' }],
  ['path', { d: 'm18 22 4-4-4-4' }],
];
