// The Lucide "clock-arrow-down" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconClockArrowDown: IconGlyph = [
  ['path', { d: 'M12 6v6l2 1' }],
  ['path', { d: 'M12.337 21.994a10 10 0 1 1 9.588-8.767' }],
  ['path', { d: 'm14 18 4 4 4-4' }],
  ['path', { d: 'M18 14v8' }],
];
