// The Lucide "clock-check" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconClockCheck: IconGlyph = [
  ['path', { d: 'M12 6v6l4 2' }],
  ['path', { d: 'M22 12a10 10 0 1 0-11 9.95' }],
  ['path', { d: 'm22 16-5.5 5.5L14 19' }],
];
