// The Lucide "clock-alert" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconClockAlert: IconGlyph = [
  ['path', { d: 'M12 6v6l4 2' }],
  ['path', { d: 'M20 12v5' }],
  ['path', { d: 'M20 21h.01' }],
  ['path', { d: 'M21.25 8.2A10 10 0 1 0 16 21.16' }],
];
