// The Lucide "closed-caption" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconClosedCaption: IconGlyph = [
  ['path', { d: 'M10 9.17a3 3 0 1 0 0 5.66' }],
  ['path', { d: 'M17 9.17a3 3 0 1 0 0 5.66' }],
  ['rect', { x: '2', y: '5', width: '20', height: '14', rx: '2' }],
];
