// The Lucide "cloud-rain-wind" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCloudRainWind: IconGlyph = [
  ['path', { d: 'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242' }],
  ['path', { d: 'm9.2 22 3-7' }],
  ['path', { d: 'm9 13-3 7' }],
  ['path', { d: 'm17 13-3 7' }],
];
