// The Lucide "coins" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCoins: IconGlyph = [
  ['path', { d: 'M13.744 17.736a6 6 0 1 1-7.48-7.48' }],
  ['path', { d: 'M15 6h1v4' }],
  ['path', { d: 'm6.134 14.768.866-.5 2 3.464' }],
  ['circle', { cx: '16', cy: '8', r: '6' }],
];
