// The Lucide "computer" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconComputer: IconGlyph = [
  ['rect', { width: '14', height: '8', x: '5', y: '2', rx: '2' }],
  ['rect', { width: '20', height: '8', x: '2', y: '14', rx: '2' }],
  ['path', { d: 'M6 18h2' }],
  ['path', { d: 'M12 18h6' }],
];
