// The Lucide "contact-round" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconContactRound: IconGlyph = [
  ['path', { d: 'M16 2v2' }],
  ['path', { d: 'M17.915 21a6 6 0 10-12 0' }],
  ['path', { d: 'M8 2v2' }],
  ['circle', { cx: '12', cy: '11', r: '4' }],
  ['rect', { x: '3', y: '3', width: '18', height: '18', rx: '2' }],
];
