// The Lucide "copyleft" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCopyleft: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '10' }],
  ['path', { d: 'M9.17 14.83a4 4 0 1 0 0-5.66' }],
];
