// The Lucide "corner-down-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCornerDownRight: IconGlyph = [
  ['path', { d: 'm15 10 5 5-5 5' }],
  ['path', { d: 'M4 4v7a4 4 0 0 0 4 4h12' }],
];
