// The Lucide "corner-up-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCornerUpLeft: IconGlyph = [
  ['path', { d: 'M20 20v-7a4 4 0 0 0-4-4H4' }],
  ['path', { d: 'M9 14 4 9l5-5' }],
];
