// The Lucide "corner-up-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCornerUpRight: IconGlyph = [
  ['path', { d: 'm15 14 5-5-5-5' }],
  ['path', { d: 'M4 20v-7a4 4 0 0 1 4-4h12' }],
];
