// The Lucide "corner-left-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCornerLeftUp: IconGlyph = [
  ['path', { d: 'M14 9 9 4 4 9' }],
  ['path', { d: 'M20 20h-7a4 4 0 0 1-4-4V4' }],
];
