// The Lucide "corner-right-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCornerRightUp: IconGlyph = [
  ['path', { d: 'm10 9 5-5 5 5' }],
  ['path', { d: 'M4 20h7a4 4 0 0 0 4-4V4' }],
];
