// The Lucide "crop" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCrop: IconGlyph = [
  ['path', { d: 'M6 2v14a2 2 0 0 0 2 2h14' }],
  ['path', { d: 'M18 22V8a2 2 0 0 0-2-2H2' }],
];
