// The Lucide "currency" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconCurrency: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '8' }],
  ['line', { x1: '3', x2: '6', y1: '3', y2: '6' }],
  ['line', { x1: '21', x2: '18', y1: '3', y2: '6' }],
  ['line', { x1: '3', x2: '6', y1: '21', y2: '18' }],
  ['line', { x1: '21', x2: '18', y1: '21', y2: '18' }],
];
