// The Lucide "database-zap" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconDatabaseZap: IconGlyph = [
  ['ellipse', { cx: '12', cy: '5', rx: '9', ry: '3' }],
  ['path', { d: 'M3 5V19A9 3 0 0 0 15 21.84' }],
  ['path', { d: 'M21 5V8' }],
  ['path', { d: 'M21 12L18 17H22L19 22' }],
  ['path', { d: 'M3 12A9 3 0 0 0 14.59 14.87' }],
];
