// The Lucide "decimals-arrow-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconDecimalsArrowLeft: IconGlyph = [
  ['path', { d: 'm13 21-3-3 3-3' }],
  ['path', { d: 'M20 18H10' }],
  ['path', { d: 'M3 11h.01' }],
  ['rect', { x: '6', y: '3', width: '5', height: '8', rx: '2.5' }],
];
