// The Lucide "decimals-arrow-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconDecimalsArrowRight: IconGlyph = [
  ['path', { d: 'M10 18h10' }],
  ['path', { d: 'm17 21 3-3-3-3' }],
  ['path', { d: 'M3 11h.01' }],
  ['rect', { x: '15', y: '3', width: '5', height: '8', rx: '2.5' }],
  ['rect', { x: '6', y: '3', width: '5', height: '8', rx: '2.5' }],
];
