// The Lucide "diff" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconDiff: IconGlyph = [
  ['path', { d: 'M12 3v14' }],
  ['path', { d: 'M5 10h14' }],
  ['path', { d: 'M5 21h14' }],
];
