// The Lucide "disc-3" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconDisc3: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '10' }],
  ['path', { d: 'M6 12c0-1.7.7-3.2 1.8-4.2' }],
  ['circle', { cx: '12', cy: '12', r: '2' }],
  ['path', { d: 'M18 12c0 1.7-.7 3.2-1.8 4.2' }],
];
