// The Lucide "divide" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconDivide: IconGlyph = [
  ['circle', { cx: '12', cy: '6', r: '1' }],
  ['line', { x1: '5', x2: '19', y1: '12', y2: '12' }],
  ['circle', { cx: '12', cy: '18', r: '1' }],
];
