// The Lucide "ellipse" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconEllipse: IconGlyph = [['ellipse', { cx: '12', cy: '12', rx: '10', ry: '6' }]];
