// The Lucide "expand" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconExpand: IconGlyph = [
  ['path', { d: 'm15 15 6 6' }],
  ['path', { d: 'm15 9 6-6' }],
  ['path', { d: 'M21 16v5h-5' }],
  ['path', { d: 'M21 8V3h-5' }],
  ['path', { d: 'M3 16v5h5' }],
  ['path', { d: 'm3 21 6-6' }],
  ['path', { d: 'M3 8V3h5' }],
  ['path', { d: 'M9 9 3 3' }],
];
