// The Lucide "eye-closed" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconEyeClosed: IconGlyph = [
  ['path', { d: 'm15 18-.722-3.25' }],
  ['path', { d: 'M2 8a10.645 10.645 0 0 0 20 0' }],
  ['path', { d: 'm20 15-1.726-2.05' }],
  ['path', { d: 'm4 15 1.726-2.05' }],
  ['path', { d: 'm9 18 .722-3.25' }],
];
