// The Lucide "face-angry" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFaceAngry: IconGlyph = [
  ['path', { d: 'M15 11V9.416' }],
  ['path', { d: 'M17 9a5 5 0 00-3 1' }],
  ['path', { d: 'M7 9a5 5 0 013 1' }],
  ['path', { d: 'M9 11V9.416' }],
  ['path', { d: 'M9 16a5 5 0 016.001 0' }],
  ['circle', { cx: '12', cy: '12', r: '10' }],
];
