// The Lucide "face-slightly-frowning" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFaceSlightlyFrowning: IconGlyph = [
  ['path', { d: 'M15 10V9' }],
  ['path', { d: 'M9 10V9' }],
  ['path', { d: 'M9 16a5 5 0 016 0' }],
  ['circle', { cx: '12', cy: '12', r: '10' }],
];
