// The Lucide "face-slightly-smiling" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFaceSlightlySmiling: IconGlyph = [
  ['path', { d: 'M15 10V9' }],
  ['path', { d: 'M16.472 15a6 6 0 01-8.943 0' }],
  ['path', { d: 'M9 10V9' }],
  ['circle', { cx: '12', cy: '12', r: '10' }],
];
