// The Lucide "file-scan" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFileScan: IconGlyph = [
  [
    'path',
    {
      d: 'M20 10V8a2.4 2.4 0 0 0-.706-1.704l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h4.35',
    },
  ],
  ['path', { d: 'M14 2v5a1 1 0 0 0 1 1h5' }],
  ['path', { d: 'M16 14a2 2 0 0 0-2 2' }],
  ['path', { d: 'M16 22a2 2 0 0 1-2-2' }],
  ['path', { d: 'M20 14a2 2 0 0 1 2 2' }],
  ['path', { d: 'M20 22a2 2 0 0 0 2-2' }],
];
