// The Lucide "fish-symbol" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFishSymbol: IconGlyph = [['path', { d: 'M2 16s9-15 20-4C11 23 2 8 2 8' }]];
