// The Lucide "flask-conical-off" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFlaskConicalOff: IconGlyph = [
  ['path', { d: 'M10 2v2.343' }],
  ['path', { d: 'M14 2v6.343' }],
  ['path', { d: 'm2 2 20 20' }],
  ['path', { d: 'M20 20a2 2 0 0 1-2 2H6a2 2 0 0 1-1.755-2.96l5.227-9.563' }],
  ['path', { d: 'M6.453 15H15' }],
  ['path', { d: 'M8.5 2h7' }],
];
