// The Lucide "flip-horizontal-2" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFlipHorizontal2: IconGlyph = [
  ['path', { d: 'm3 7 5 5-5 5V7' }],
  ['path', { d: 'm21 7-5 5 5 5V7' }],
  ['path', { d: 'M12 20v2' }],
  ['path', { d: 'M12 14v2' }],
  ['path', { d: 'M12 8v2' }],
  ['path', { d: 'M12 2v2' }],
];
