// The Lucide "flip-vertical-2" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFlipVertical2: IconGlyph = [
  ['path', { d: 'm17 3-5 5-5-5h10' }],
  ['path', { d: 'm17 21-5-5-5 5h10' }],
  ['path', { d: 'M4 12H2' }],
  ['path', { d: 'M10 12H8' }],
  ['path', { d: 'M16 12h-2' }],
  ['path', { d: 'M22 12h-2' }],
];
