// The Lucide "fold-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFoldHorizontal: IconGlyph = [
  ['path', { d: 'M2 12h6' }],
  ['path', { d: 'M22 12h-6' }],
  ['path', { d: 'M12 2v2' }],
  ['path', { d: 'M12 8v2' }],
  ['path', { d: 'M12 14v2' }],
  ['path', { d: 'M12 20v2' }],
  ['path', { d: 'm19 9-3 3 3 3' }],
  ['path', { d: 'm5 15 3-3-3-3' }],
];
