// The Lucide "fold-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFoldVertical: IconGlyph = [
  ['path', { d: 'M12 22v-6' }],
  ['path', { d: 'M12 8V2' }],
  ['path', { d: 'M4 12H2' }],
  ['path', { d: 'M10 12H8' }],
  ['path', { d: 'M16 12h-2' }],
  ['path', { d: 'M22 12h-2' }],
  ['path', { d: 'm15 19-3-3-3 3' }],
  ['path', { d: 'm15 5-3 3-3-3' }],
];
