// The Lucide "form" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconForm: IconGlyph = [
  ['path', { d: 'M4 14h6' }],
  ['path', { d: 'M4 2h10' }],
  ['rect', { x: '4', y: '18', width: '16', height: '4', rx: '1' }],
  ['rect', { x: '4', y: '6', width: '16', height: '4', rx: '1' }],
];
