// The Lucide "forward" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconForward: IconGlyph = [
  ['path', { d: 'm15 17 5-5-5-5' }],
  ['path', { d: 'M4 18v-2a4 4 0 0 1 4-4h12' }],
];
