// The Lucide "frame" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconFrame: IconGlyph = [
  ['line', { x1: '22', x2: '2', y1: '6', y2: '6' }],
  ['line', { x1: '22', x2: '2', y1: '18', y2: '18' }],
  ['line', { x1: '6', x2: '6', y1: '2', y2: '22' }],
  ['line', { x1: '18', x2: '18', y1: '2', y2: '22' }],
];
