// The Lucide "gallery-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGalleryVertical: IconGlyph = [
  ['path', { d: 'M3 2h18' }],
  ['rect', { width: '18', height: '12', x: '3', y: '6', rx: '2' }],
  ['path', { d: 'M3 22h18' }],
];
