// The Lucide "gallery-thumbnails" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGalleryThumbnails: IconGlyph = [
  ['rect', { width: '18', height: '14', x: '3', y: '3', rx: '2' }],
  ['path', { d: 'M4 21h1' }],
  ['path', { d: 'M9 21h1' }],
  ['path', { d: 'M14 21h1' }],
  ['path', { d: 'M19 21h1' }],
];
