// The Lucide "gallery-vertical-end" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGalleryVerticalEnd: IconGlyph = [
  ['path', { d: 'M7 2h10' }],
  ['path', { d: 'M5 6h14' }],
  ['rect', { width: '18', height: '12', x: '3', y: '10', rx: '2' }],
];
