// The Lucide "gallery-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGalleryHorizontal: IconGlyph = [
  ['path', { d: 'M2 3v18' }],
  ['rect', { width: '12', height: '18', x: '6', y: '3', rx: '2' }],
  ['path', { d: 'M22 3v18' }],
];
