// The Lucide "gauge" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGauge: IconGlyph = [
  ['path', { d: 'm12 14 4-4' }],
  ['path', { d: 'M3.34 19a10 10 0 1 1 17.32 0' }],
];
