// The Lucide "georgian-lari" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGeorgianLari: IconGlyph = [
  ['path', { d: 'M11.5 21a7.5 7.5 0 1 1 7.35-9' }],
  ['path', { d: 'M13 12V3' }],
  ['path', { d: 'M4 21h16' }],
  ['path', { d: 'M9 12V3' }],
];
