// The Lucide "git-pull-request-create-arrow" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitPullRequestCreateArrow: IconGlyph = [
  ['circle', { cx: '5', cy: '6', r: '3' }],
  ['path', { d: 'M5 9v12' }],
  ['path', { d: 'm15 9-3-3 3-3' }],
  ['path', { d: 'M12 6h5a2 2 0 0 1 2 2v3' }],
  ['path', { d: 'M19 15v6' }],
  ['path', { d: 'M22 18h-6' }],
];
