// The Lucide "git-commit-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitCommitVertical: IconGlyph = [
  ['path', { d: 'M12 3v6' }],
  ['circle', { cx: '12', cy: '12', r: '3' }],
  ['path', { d: 'M12 15v6' }],
];
