// The Lucide "git-compare-arrows" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitCompareArrows: IconGlyph = [
  ['circle', { cx: '5', cy: '6', r: '3' }],
  ['path', { d: 'M12 6h5a2 2 0 0 1 2 2v7' }],
  ['path', { d: 'm15 9-3-3 3-3' }],
  ['circle', { cx: '19', cy: '18', r: '3' }],
  ['path', { d: 'M12 18H7a2 2 0 0 1-2-2V9' }],
  ['path', { d: 'm9 15 3 3-3 3' }],
];
