// The Lucide "git-pull-request-create" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitPullRequestCreate: IconGlyph = [
  ['circle', { cx: '6', cy: '6', r: '3' }],
  ['path', { d: 'M6 9v12' }],
  ['path', { d: 'M13 6h3a2 2 0 0 1 2 2v3' }],
  ['path', { d: 'M18 15v6' }],
  ['path', { d: 'M21 18h-6' }],
];
