// The Lucide "git-commit-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitCommitHorizontal: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '3' }],
  ['line', { x1: '3', x2: '9', y1: '12', y2: '12' }],
  ['line', { x1: '15', x2: '21', y1: '12', y2: '12' }],
];
