// The Lucide "git-branch-minus" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitBranchMinus: IconGlyph = [
  ['path', { d: 'M15 6a9 9 0 0 0-9 9V3' }],
  ['path', { d: 'M21 18h-6' }],
  ['circle', { cx: '18', cy: '6', r: '3' }],
  ['circle', { cx: '6', cy: '18', r: '3' }],
];
