// The Lucide "git-graph" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitGraph: IconGlyph = [
  ['circle', { cx: '5', cy: '6', r: '3' }],
  ['path', { d: 'M5 9v6' }],
  ['circle', { cx: '5', cy: '18', r: '3' }],
  ['path', { d: 'M12 3v18' }],
  ['circle', { cx: '19', cy: '6', r: '3' }],
  ['path', { d: 'M16 15.7A9 9 0 0 0 19 9' }],
];
