// The Lucide "git-merge-conflict" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGitMergeConflict: IconGlyph = [
  ['path', { d: 'M12 6h4a2 2 0 0 1 2 2v7' }],
  ['path', { d: 'M6 12v9' }],
  ['path', { d: 'M9 3 3 9' }],
  ['path', { d: 'M9 9 3 3' }],
  ['circle', { cx: '18', cy: '18', r: '3' }],
];
