// The Lucide "goal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGoal: IconGlyph = [
  ['path', { d: 'M12 13V2l8 4-8 4' }],
  ['path', { d: 'M20.561 10.222a9 9 0 1 1-12.55-5.29' }],
  ['path', { d: 'M8.002 9.997a5 5 0 1 0 8.9 2.02' }],
];
