// The Lucide "grip-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconGripHorizontal: IconGlyph = [
  ['circle', { cx: '12', cy: '9', r: '1' }],
  ['circle', { cx: '19', cy: '9', r: '1' }],
  ['circle', { cx: '5', cy: '9', r: '1' }],
  ['circle', { cx: '12', cy: '15', r: '1' }],
  ['circle', { cx: '19', cy: '15', r: '1' }],
  ['circle', { cx: '5', cy: '15', r: '1' }],
];
