// The Lucide "hash" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconHash: IconGlyph = [
  ['line', { x1: '4', x2: '20', y1: '9', y2: '9' }],
  ['line', { x1: '4', x2: '20', y1: '15', y2: '15' }],
  ['line', { x1: '10', x2: '8', y1: '3', y2: '21' }],
  ['line', { x1: '16', x2: '14', y1: '3', y2: '21' }],
];
