// The Lucide "heading" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconHeading: IconGlyph = [
  ['path', { d: 'M6 12h12' }],
  ['path', { d: 'M6 20V4' }],
  ['path', { d: 'M18 20V4' }],
];
