// The Lucide "heading-6" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconHeading6: IconGlyph = [
  ['path', { d: 'M4 12h8' }],
  ['path', { d: 'M4 18V6' }],
  ['path', { d: 'M12 18V6' }],
  ['circle', { cx: '19', cy: '16', r: '2' }],
  ['path', { d: 'M20 10c-2 2-3 3.5-3 6' }],
];
