// The Lucide "italic" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconItalic: IconGlyph = [
  ['line', { x1: '19', x2: '10', y1: '4', y2: '4' }],
  ['line', { x1: '14', x2: '5', y1: '20', y2: '20' }],
  ['line', { x1: '15', x2: '9', y1: '4', y2: '20' }],
];
