// The Lucide "iteration-cw" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconIterationCw: IconGlyph = [
  ['path', { d: 'M4 10a8 8 0 1 1 8 8H4' }],
  ['path', { d: 'm8 22-4-4 4-4' }],
];
