// The Lucide "iteration-ccw" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconIterationCcw: IconGlyph = [
  ['path', { d: 'm16 14 4 4-4 4' }],
  ['path', { d: 'M20 10a8 8 0 1 0-8 8h8' }],
];
