// The Lucide "kanban" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconKanban: IconGlyph = [
  ['path', { d: 'M5 3v14' }],
  ['path', { d: 'M12 3v8' }],
  ['path', { d: 'M19 3v18' }],
];
