// The Lucide "lamp-ceiling" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLampCeiling: IconGlyph = [
  ['path', { d: 'M12 2v5' }],
  ['path', { d: 'M14.829 15.998a3 3 0 1 1-5.658 0' }],
  [
    'path',
    {
      d: 'M20.92 14.606A1 1 0 0 1 20 16H4a1 1 0 0 1-.92-1.394l3-7A1 1 0 0 1 7 7h10a1 1 0 0 1 .92.606z',
    },
  ],
];
