// The Lucide "laptop-minimal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLaptopMinimal: IconGlyph = [
  ['rect', { width: '18', height: '12', x: '3', y: '4', rx: '2', ry: '2' }],
  ['line', { x1: '2', x2: '22', y1: '20', y2: '20' }],
];
