// The Lucide "lasso" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLasso: IconGlyph = [
  ['path', { d: 'M3.704 14.467a10 8 0 1 1 3.115 2.375' }],
  ['path', { d: 'M7 22a5 5 0 0 1-2-3.994' }],
  ['circle', { cx: '5', cy: '16', r: '2' }],
];
