// The Lucide "layer-arrow-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLayerArrowUp: IconGlyph = [
  ['path', { d: 'M12 14V4' }],
  [
    'path',
    {
      d: 'M7.674 10.774 2.58 13.09a1 1 0 000 1.822l8.6 3.91a2 2 0 001.65 0l8.58-3.9a1 1 0 00.59-.92 1 1 0 00-.59-.922l-5.078-2.308',
    },
  ],
  ['path', { d: 'm9 7 3-3 3 3' }],
];
