// The Lucide "layout-list" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLayoutList: IconGlyph = [
  ['rect', { width: '7', height: '7', x: '3', y: '3', rx: '1' }],
  ['rect', { width: '7', height: '7', x: '3', y: '14', rx: '1' }],
  ['path', { d: 'M14 4h7' }],
  ['path', { d: 'M14 9h7' }],
  ['path', { d: 'M14 15h7' }],
  ['path', { d: 'M14 20h7' }],
];
