// The Lucide "library" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLibrary: IconGlyph = [
  ['path', { d: 'm16 6 4 14' }],
  ['path', { d: 'M12 6v14' }],
  ['path', { d: 'M8 8v12' }],
  ['path', { d: 'M4 4v16' }],
];
