// The Lucide "life-buoy" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLifeBuoy: IconGlyph = [
  ['circle', { cx: '12', cy: '12', r: '10' }],
  ['path', { d: 'm4.93 4.93 4.24 4.24' }],
  ['path', { d: 'm14.83 9.17 4.24-4.24' }],
  ['path', { d: 'm14.83 14.83 4.24 4.24' }],
  ['path', { d: 'm9.17 14.83-4.24 4.24' }],
  ['circle', { cx: '12', cy: '12', r: '4' }],
];
