// The Lucide "ligature" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLigature: IconGlyph = [
  ['path', { d: 'M14 12h2v8' }],
  ['path', { d: 'M14 20h4' }],
  ['path', { d: 'M6 12h4' }],
  ['path', { d: 'M6 20h4' }],
  ['path', { d: 'M8 20V8a4 4 0 0 1 7.464-2' }],
];
