// The Lucide "line-dot-right-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLineDotRightHorizontal: IconGlyph = [
  ['path', { d: 'M 3 12 L 15 12' }],
  ['circle', { cx: '18', cy: '12', r: '3' }],
];
