// The Lucide "line-style" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLineStyle: IconGlyph = [
  ['path', { d: 'M11 5h2' }],
  ['path', { d: 'M15 12h6' }],
  ['path', { d: 'M19 5h2' }],
  ['path', { d: 'M3 12h6' }],
  ['path', { d: 'M3 19h18' }],
  ['path', { d: 'M3 5h2' }],
];
