// The Lucide "list-end" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListEnd: IconGlyph = [
  ['path', { d: 'M16 5H3' }],
  ['path', { d: 'M16 12H3' }],
  ['path', { d: 'M9 19H3' }],
  ['path', { d: 'm16 16-3 3 3 3' }],
  ['path', { d: 'M21 5v12a2 2 0 0 1-2 2h-6' }],
];
