// The Lucide "list-sort-descending" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListSortDescending: IconGlyph = [
  ['path', { d: 'M15 12H3' }],
  ['path', { d: 'M3 5h18' }],
  ['path', { d: 'M9 19H3' }],
];
