// The Lucide "list-tree" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListTree: IconGlyph = [
  ['path', { d: 'M8 5h13' }],
  ['path', { d: 'M13 12h8' }],
  ['path', { d: 'M13 19h8' }],
  ['path', { d: 'M3 10a2 2 0 0 0 2 2h3' }],
  ['path', { d: 'M3 5v12a2 2 0 0 0 2 2h3' }],
];
