// The Lucide "list-restart" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListRestart: IconGlyph = [
  ['path', { d: 'M21 5H3' }],
  ['path', { d: 'M7 12H3' }],
  ['path', { d: 'M7 19H3' }],
  ['path', { d: 'M12 18a5 5 0 0 0 9-3 4.5 4.5 0 0 0-4.5-4.5c-1.33 0-2.54.54-3.41 1.41L11 14' }],
  ['path', { d: 'M11 10v4h4' }],
];
