// The Lucide "list-filter-plus" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListFilterPlus: IconGlyph = [
  ['path', { d: 'M12 5H2' }],
  ['path', { d: 'M6 12h12' }],
  ['path', { d: 'M9 19h6' }],
  ['path', { d: 'M16 5h6' }],
  ['path', { d: 'M19 8V2' }],
];
