// The Lucide "list-chevrons-down-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListChevronsDownUp: IconGlyph = [
  ['path', { d: 'M3 5h8' }],
  ['path', { d: 'M3 12h8' }],
  ['path', { d: 'M3 19h8' }],
  ['path', { d: 'm15 5 3 3 3-3' }],
  ['path', { d: 'm15 19 3-3 3 3' }],
];
