// The Lucide "list-indent-decrease" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListIndentDecrease: IconGlyph = [
  ['path', { d: 'M21 5H11' }],
  ['path', { d: 'M21 12H11' }],
  ['path', { d: 'M21 19H11' }],
  ['path', { d: 'm7 8-4 4 4 4' }],
];
