// The Lucide "list-collapse" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListCollapse: IconGlyph = [
  ['path', { d: 'M10 5h11' }],
  ['path', { d: 'M10 12h11' }],
  ['path', { d: 'M10 19h11' }],
  ['path', { d: 'm3 10 3-3-3-3' }],
  ['path', { d: 'm3 20 3-3-3-3' }],
];
