// The Lucide "list-sort-ascending" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconListSortAscending: IconGlyph = [
  ['path', { d: 'M3 19h18' }],
  ['path', { d: 'M15 12H3' }],
  ['path', { d: 'M9 5H3' }],
];
