// The Lucide "loader-circle" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLoaderCircle: IconGlyph = [['path', { d: 'M21 12a9 9 0 1 1-6.219-8.56' }]];
