// The Lucide "lock-keyhole" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLockKeyhole: IconGlyph = [
  ['circle', { cx: '12', cy: '16', r: '1' }],
  ['rect', { x: '3', y: '10', width: '18', height: '12', rx: '2' }],
  ['path', { d: 'M7 10V7a5 5 0 0 1 10 0v3' }],
];
