// The Lucide "log-in" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLogIn: IconGlyph = [
  ['path', { d: 'm10 17 5-5-5-5' }],
  ['path', { d: 'M15 12H3' }],
  ['path', { d: 'M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4' }],
];
