// The Lucide "logs" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconLogs: IconGlyph = [
  ['path', { d: 'M3 5h1' }],
  ['path', { d: 'M3 12h1' }],
  ['path', { d: 'M3 19h1' }],
  ['path', { d: 'M8 5h1' }],
  ['path', { d: 'M8 12h1' }],
  ['path', { d: 'M8 19h1' }],
  ['path', { d: 'M13 5h8' }],
  ['path', { d: 'M13 12h8' }],
  ['path', { d: 'M13 19h8' }],
];
