// The Lucide "mars" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMars: IconGlyph = [
  ['path', { d: 'M16 3h5v5' }],
  ['path', { d: 'm21 3-6.75 6.75' }],
  ['circle', { cx: '10', cy: '14', r: '6' }],
];
