// The Lucide "mars-stroke" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMarsStroke: IconGlyph = [
  ['path', { d: 'm14 6 4 4' }],
  ['path', { d: 'M17 3h4v4' }],
  ['path', { d: 'm21 3-7.75 7.75' }],
  ['circle', { cx: '9', cy: '15', r: '6' }],
];
