// The Lucide "merge" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMerge: IconGlyph = [
  ['path', { d: 'm8 6 4-4 4 4' }],
  ['path', { d: 'M12 2v10.3a4 4 0 0 1-1.172 2.872L4 22' }],
  ['path', { d: 'm20 22-5-5' }],
];
