// The Lucide "mic" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMic: IconGlyph = [
  ['path', { d: 'M12 19v3' }],
  ['path', { d: 'M19 10v2a7 7 0 0 1-14 0v-2' }],
  ['rect', { x: '9', y: '2', width: '6', height: '13', rx: '3' }],
];
