// The Lucide "microchip" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMicrochip: IconGlyph = [
  ['path', { d: 'M10 12h4' }],
  ['path', { d: 'M10 17h4' }],
  ['path', { d: 'M10 7h4' }],
  ['path', { d: 'M18 12h2' }],
  ['path', { d: 'M18 18h2' }],
  ['path', { d: 'M18 6h2' }],
  ['path', { d: 'M4 12h2' }],
  ['path', { d: 'M4 18h2' }],
  ['path', { d: 'M4 6h2' }],
  ['rect', { x: '6', y: '2', width: '12', height: '20', rx: '2' }],
];
