// The Lucide "minimize" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMinimize: IconGlyph = [
  ['path', { d: 'M8 3v3a2 2 0 0 1-2 2H3' }],
  ['path', { d: 'M21 8h-3a2 2 0 0 1-2-2V3' }],
  ['path', { d: 'M3 16h3a2 2 0 0 1 2 2v3' }],
  ['path', { d: 'M16 21v-3a2 2 0 0 1 2-2h3' }],
];
