// The Lucide "minimize-2" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMinimize2: IconGlyph = [
  ['path', { d: 'm14 10 7-7' }],
  ['path', { d: 'M20 10h-6V4' }],
  ['path', { d: 'm3 21 7-7' }],
  ['path', { d: 'M4 14h6v6' }],
];
