// The Lucide "monitor-dot" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMonitorDot: IconGlyph = [
  ['path', { d: 'M12 17v4' }],
  ['path', { d: 'M22 12.307V15a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h8.693' }],
  ['path', { d: 'M8 21h8' }],
  ['circle', { cx: '19', cy: '6', r: '3' }],
];
