// The Lucide "mouse-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMouseRight: IconGlyph = [
  ['path', { d: 'M12 7.318V10' }],
  ['path', { d: 'M19 10v5a7 7 0 0 1-14 0V9c0-3.527 2.608-6.515 6-7' }],
  ['circle', { cx: '17', cy: '4', r: '2' }],
];
