// The Lucide "move-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMoveVertical: IconGlyph = [
  ['path', { d: 'M12 2v20' }],
  ['path', { d: 'm8 18 4 4 4-4' }],
  ['path', { d: 'm8 6 4-4 4 4' }],
];
