// The Lucide "move" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMove: IconGlyph = [
  ['path', { d: 'M12 2v20' }],
  ['path', { d: 'm15 19-3 3-3-3' }],
  ['path', { d: 'm19 9 3 3-3 3' }],
  ['path', { d: 'M2 12h20' }],
  ['path', { d: 'm5 9-3 3 3 3' }],
  ['path', { d: 'm9 5 3-3 3 3' }],
];
