// The Lucide "move-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMoveHorizontal: IconGlyph = [
  ['path', { d: 'm18 8 4 4-4 4' }],
  ['path', { d: 'M2 12h20' }],
  ['path', { d: 'm6 8-4 4 4 4' }],
];
