// The Lucide "move-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMoveRight: IconGlyph = [
  ['path', { d: 'M18 8L22 12L18 16' }],
  ['path', { d: 'M2 12H22' }],
];
