// The Lucide "move-up-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMoveUpLeft: IconGlyph = [
  ['path', { d: 'M5 11V5H11' }],
  ['path', { d: 'M5 5L19 19' }],
];
