// The Lucide "move-down" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMoveDown: IconGlyph = [
  ['path', { d: 'M8 18L12 22L16 18' }],
  ['path', { d: 'M12 2V22' }],
];
