// The Lucide "move-up" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMoveUp: IconGlyph = [
  ['path', { d: 'M8 6L12 2L16 6' }],
  ['path', { d: 'M12 2V22' }],
];
