// The Lucide "music-3" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMusic3: IconGlyph = [
  ['circle', { cx: '12', cy: '18', r: '4' }],
  ['path', { d: 'M16 18V2' }],
];
