// The Lucide "music-2" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconMusic2: IconGlyph = [
  ['circle', { cx: '8', cy: '18', r: '4' }],
  ['path', { d: 'M12 18V2l7 4' }],
];
