// The Lucide "navigation" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconNavigation: IconGlyph = [['polygon', { points: '3 11 22 2 13 21 11 13 3 11' }]];
