// The Lucide "navigation-off" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconNavigationOff: IconGlyph = [
  ['path', { d: 'M8.43 8.43 3 11l8 2 2 8 2.57-5.43' }],
  ['path', { d: 'M17.39 11.73 22 2l-9.73 4.61' }],
  ['line', { x1: '2', x2: '22', y1: '2', y2: '22' }],
];
