// The Lucide "non-binary" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconNonBinary: IconGlyph = [
  ['path', { d: 'M12 2v10' }],
  ['path', { d: 'm8.5 4 7 4' }],
  ['path', { d: 'm8.5 8 7-4' }],
  ['circle', { cx: '12', cy: '17', r: '5' }],
];
