// The Lucide "notepad-text" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconNotepadText: IconGlyph = [
  ['path', { d: 'M8 2v4' }],
  ['path', { d: 'M12 2v4' }],
  ['path', { d: 'M16 2v4' }],
  ['rect', { width: '16', height: '18', x: '4', y: '4', rx: '2' }],
  ['path', { d: 'M8 10h6' }],
  ['path', { d: 'M8 14h8' }],
  ['path', { d: 'M8 18h5' }],
];
