// The Lucide "panel-left-right-dashed" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPanelLeftRightDashed: IconGlyph = [
  ['path', { d: 'M15 10V9' }],
  ['path', { d: 'M15 15v-1' }],
  ['path', { d: 'M15 21v-2' }],
  ['path', { d: 'M15 5V3' }],
  ['path', { d: 'M9 10V9' }],
  ['path', { d: 'M9 15v-1' }],
  ['path', { d: 'M9 21v-2' }],
  ['path', { d: 'M9 5V3' }],
  ['rect', { x: '3', y: '3', width: '18', height: '18', rx: '2' }],
];
