// The Lucide "panel-right-dashed" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPanelRightDashed: IconGlyph = [
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
  ['path', { d: 'M15 14v1' }],
  ['path', { d: 'M15 19v2' }],
  ['path', { d: 'M15 3v2' }],
  ['path', { d: 'M15 9v1' }],
];
