// The Lucide "panel-top-dashed" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPanelTopDashed: IconGlyph = [
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
  ['path', { d: 'M14 9h1' }],
  ['path', { d: 'M19 9h2' }],
  ['path', { d: 'M3 9h2' }],
  ['path', { d: 'M9 9h1' }],
];
