// The Lucide "pc-case" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPcCase: IconGlyph = [
  ['rect', { width: '14', height: '20', x: '5', y: '2', rx: '2' }],
  ['path', { d: 'M15 14h.01' }],
  ['path', { d: 'M9 6h6' }],
  ['path', { d: 'M9 10h6' }],
];
