// The Lucide "percent" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPercent: IconGlyph = [
  ['line', { x1: '19', x2: '5', y1: '5', y2: '19' }],
  ['circle', { cx: '6.5', cy: '6.5', r: '2.5' }],
  ['circle', { cx: '17.5', cy: '17.5', r: '2.5' }],
];
