// The Lucide "pi" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPi: IconGlyph = [
  ['line', { x1: '9', x2: '9', y1: '4', y2: '20' }],
  ['path', { d: 'M4 7c0-1.7 1.3-3 3-3h13' }],
  ['path', { d: 'M18 20c-1.7 0-3-1.3-3-3V4' }],
];
