// The Lucide "pilcrow-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPilcrowLeft: IconGlyph = [
  ['path', { d: 'M14 3v11' }],
  ['path', { d: 'M14 9h-3a3 3 0 0 1 0-6h9' }],
  ['path', { d: 'M18 3v11' }],
  ['path', { d: 'M22 18H2l4-4' }],
  ['path', { d: 'm6 22-4-4' }],
];
