// The Lucide "pound-sterling" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPoundSterling: IconGlyph = [
  ['path', { d: 'M18 7c0-5.333-8-5.333-8 0' }],
  ['path', { d: 'M10 7v14' }],
  ['path', { d: 'M6 21h12' }],
  ['path', { d: 'M6 13h10' }],
];
