// The Lucide "power-off" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPowerOff: IconGlyph = [
  ['path', { d: 'M18.36 6.64A9 9 0 0 1 20.77 15' }],
  ['path', { d: 'M6.16 6.16a9 9 0 1 0 12.68 12.68' }],
  ['path', { d: 'M12 2v4' }],
  ['path', { d: 'm2 2 20 20' }],
];
