// The Lucide "presentation" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconPresentation: IconGlyph = [
  ['path', { d: 'M2 3h20' }],
  ['path', { d: 'M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3' }],
  ['path', { d: 'm7 21 5-5 5 5' }],
];
