// The Lucide "radio-receiver" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRadioReceiver: IconGlyph = [
  ['path', { d: 'M5 16v2' }],
  ['path', { d: 'M19 16v2' }],
  ['rect', { width: '20', height: '8', x: '2', y: '8', rx: '2' }],
  ['path', { d: 'M18 12h.01' }],
];
