// The Lucide "rainbow" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRainbow: IconGlyph = [
  ['path', { d: 'M22 17a10 10 0 0 0-20 0' }],
  ['path', { d: 'M6 17a6 6 0 0 1 12 0' }],
  ['path', { d: 'M10 17a2 2 0 0 1 4 0' }],
];
