// The Lucide "rectangle-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRectangleVertical: IconGlyph = [
  ['rect', { width: '12', height: '20', x: '6', y: '2', rx: '2' }],
];
