// The Lucide "rectangle-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRectangleHorizontal: IconGlyph = [
  ['rect', { width: '20', height: '12', x: '2', y: '6', rx: '2' }],
];
