// The Lucide "repeat-2" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRepeat2: IconGlyph = [
  ['path', { d: 'm2 9 3-3 3 3' }],
  ['path', { d: 'M13 18H7a2 2 0 0 1-2-2V6' }],
  ['path', { d: 'm22 15-3 3-3-3' }],
  ['path', { d: 'M11 6h6a2 2 0 0 1 2 2v10' }],
];
