// The Lucide "rocking-chair" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRockingChair: IconGlyph = [
  ['path', { d: 'm15 13 3.708 7.416' }],
  ['path', { d: 'M3 19a15 15 0 0 0 18 0' }],
  ['path', { d: 'm3 2 3.21 9.633A2 2 0 0 0 8.109 13H18' }],
  ['path', { d: 'm9 13-3.708 7.416' }],
];
