// The Lucide "rotate-3d" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRotate3d: IconGlyph = [
  ['path', { d: 'm15.194 13.707 3.814 1.86-1.86 3.814' }],
  ['path', { d: 'M16.47214 7.52786 A 5 10 0 1 0 13 21.79796' }],
  ['path', { d: 'M21.79796 11 A 10 5 0 1 0 19 15.57071' }],
];
