// The Lucide "rotate-cw-square" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRotateCwSquare: IconGlyph = [
  ['path', { d: 'M12 5H6a2 2 0 0 0-2 2v3' }],
  ['path', { d: 'm9 8 3-3-3-3' }],
  ['path', { d: 'M4 14v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2' }],
];
