// The Lucide "rss" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconRss: IconGlyph = [
  ['path', { d: 'M4 11a9 9 0 0 1 9 9' }],
  ['path', { d: 'M4 4a16 16 0 0 1 16 16' }],
  ['circle', { cx: '5', cy: '19', r: '1' }],
];
