// The Lucide "save-plus" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSavePlus: IconGlyph = [
  [
    'path',
    {
      d: 'M12.5 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h10.2a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V12',
    },
  ],
  ['path', { d: 'M16 13H8a1 1 0 0 0-1 1v7' }],
  ['path', { d: 'M19 22v-6' }],
  ['path', { d: 'M22 19h-6' }],
  ['path', { d: 'M7 3v4a1 1 0 0 0 1 1h7' }],
];
