// The Lucide "scooter" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconScooter: IconGlyph = [
  ['path', { d: 'M21 4h-3.5l2 11.05' }],
  ['path', { d: 'M6.95 17h5.142c.523 0 .95-.406 1.063-.916a6.5 6.5 0 0 1 5.345-5.009' }],
  ['circle', { cx: '19.5', cy: '17.5', r: '2.5' }],
  ['circle', { cx: '4.5', cy: '17.5', r: '2.5' }],
];
