// The Lucide "separator-horizontal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSeparatorHorizontal: IconGlyph = [
  ['path', { d: 'm16 16-4 4-4-4' }],
  ['path', { d: 'M3 12h18' }],
  ['path', { d: 'm8 8 4-4 4 4' }],
];
