// The Lucide "separator-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSeparatorVertical: IconGlyph = [
  ['path', { d: 'M12 3v18' }],
  ['path', { d: 'm16 16 4-4-4-4' }],
  ['path', { d: 'm8 8-4 4 4 4' }],
];
