// The Lucide "sheet" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSheet: IconGlyph = [
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2', ry: '2' }],
  ['line', { x1: '3', x2: '21', y1: '9', y2: '9' }],
  ['line', { x1: '3', x2: '21', y1: '15', y2: '15' }],
  ['line', { x1: '9', x2: '9', y1: '9', y2: '21' }],
  ['line', { x1: '15', x2: '15', y1: '9', y2: '21' }],
];
