// The Lucide "sliders-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSlidersVertical: IconGlyph = [
  ['path', { d: 'M10 8h4' }],
  ['path', { d: 'M12 21v-9' }],
  ['path', { d: 'M12 8V3' }],
  ['path', { d: 'M17 16h4' }],
  ['path', { d: 'M19 12V3' }],
  ['path', { d: 'M19 21v-5' }],
  ['path', { d: 'M3 14h4' }],
  ['path', { d: 'M5 10V3' }],
  ['path', { d: 'M5 21v-7' }],
];
