// The Lucide "square-off" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareOff: IconGlyph = [
  ['path', { d: 'M20.4 20.4a2 2 0 01-1.4.6H5a2 2 0 01-2-2V5a2 2 0 01.59-1.41' }],
  ['path', { d: 'M21 15.3V5a2 2 0 00-2-2H8.7' }],
  ['path', { d: 'M22 22 2 2' }],
];
