// The Lucide "square-user-round" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareUserRound: IconGlyph = [
  ['path', { d: 'M18 21a6 6 0 0 0-12 0' }],
  ['circle', { cx: '12', cy: '11', r: '4' }],
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
];
