// The Lucide "square-asterisk" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareAsterisk: IconGlyph = [
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
  ['path', { d: 'M12 8v8' }],
  ['path', { d: 'm8.5 14 7-4' }],
  ['path', { d: 'm8.5 10 7 4' }],
];
