// The Lucide "square-arrow-down-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareArrowDownRight: IconGlyph = [
  ['path', { d: 'M15 15 9 9' }],
  ['path', { d: 'M9 15h6V9' }],
  ['rect', { x: '3', y: '3', width: '18', height: '18', rx: '2' }],
];
