// The Lucide "square-arrow-up-right" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareArrowUpRight: IconGlyph = [
  ['path', { d: 'M15 15V9H9' }],
  ['path', { d: 'm9 15 6-6' }],
  ['rect', { x: '3', y: '3', width: '18', height: '18', rx: '2' }],
];
