// The Lucide "square-arrow-right-exit" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareArrowRightExit: IconGlyph = [
  ['path', { d: 'M10 12h11' }],
  ['path', { d: 'm17 16 4-4-4-4' }],
  [
    'path',
    { d: 'M21 6.344V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-1.344' },
  ],
];
