// The Lucide "square-library" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareLibrary: IconGlyph = [
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
  ['path', { d: 'M7 7v10' }],
  ['path', { d: 'M11 7v10' }],
  ['path', { d: 'm15 7 2 10' }],
];
