// The Lucide "square-arrow-out-up-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareArrowOutUpLeft: IconGlyph = [
  ['path', { d: 'M13 3h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-6' }],
  ['path', { d: 'm3 3 9 9' }],
  ['path', { d: 'M3 9V3h6' }],
];
