// The Lucide "square-radical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareRadical: IconGlyph = [
  ['path', { d: 'M7 12h2l2 5 2-10h4' }],
  ['rect', { x: '3', y: '3', width: '18', height: '18', rx: '2' }],
];
