// The Lucide "square-pause" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquarePause: IconGlyph = [
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
  ['line', { x1: '10', x2: '10', y1: '15', y2: '9' }],
  ['line', { x1: '14', x2: '14', y1: '15', y2: '9' }],
];
