// The Lucide "square-dashed-bottom-code" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSquareDashedBottomCode: IconGlyph = [
  ['path', { d: 'M10 9.5 8 12l2 2.5' }],
  ['path', { d: 'M14 21h1' }],
  ['path', { d: 'm14 9.5 2 2.5-2 2.5' }],
  ['path', { d: 'M5 21a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2' }],
  ['path', { d: 'M9 21h1' }],
];
