// The Lucide "sticky-note-check" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconStickyNoteCheck: IconGlyph = [
  ['path', { d: 'm15 19 2 2 4-4' }],
  ['path', { d: 'M15 3v5a1 1 0 0 0 1 1h5' }],
  [
    'path',
    {
      d: 'M21 13V9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6.5',
    },
  ],
];
