// The Lucide "stretch-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconStretchVertical: IconGlyph = [
  ['rect', { width: '6', height: '20', x: '4', y: '2', rx: '2' }],
  ['rect', { width: '6', height: '20', x: '14', y: '2', rx: '2' }],
];
