// The Lucide "summary" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSummary: IconGlyph = [
  ['path', { d: 'M15 4H7' }],
  ['path', { d: 'm18 16 3 3-3 3' }],
  ['path', { d: 'M3 4v13a2 2 0 0 0 2 2h16' }],
  ['path', { d: 'M7 14h7' }],
  ['path', { d: 'M7 9h12' }],
];
