// The Lucide "swiss-franc" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSwissFranc: IconGlyph = [
  ['path', { d: 'M10 21V3h8' }],
  ['path', { d: 'M6 16h9' }],
  ['path', { d: 'M10 9.5h7' }],
];
