// The Lucide "switch-camera" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSwitchCamera: IconGlyph = [
  ['path', { d: 'M11 19H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h5' }],
  ['path', { d: 'M13 5h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-5' }],
  ['circle', { cx: '12', cy: '12', r: '3' }],
  ['path', { d: 'm18 22-3-3 3-3' }],
  ['path', { d: 'm6 2 3 3-3 3' }],
];
