// The Lucide "sword" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconSword: IconGlyph = [
  ['path', { d: 'm11 19-6-6' }],
  ['path', { d: 'm5 21-2-2' }],
  ['path', { d: 'm8 16-4 4' }],
  ['path', { d: 'M9.5 17.5 21 6V3h-3L6.5 14.5' }],
];
