// The Lucide "table-cells-merge" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTableCellsMerge: IconGlyph = [
  ['path', { d: 'M12 21v-6' }],
  ['path', { d: 'M12 9V3' }],
  ['path', { d: 'M3 15h18' }],
  ['path', { d: 'M3 9h18' }],
  ['rect', { width: '18', height: '18', x: '3', y: '3', rx: '2' }],
];
