// The Lucide "tablet-smartphone" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTabletSmartphone: IconGlyph = [
  ['rect', { width: '10', height: '14', x: '3', y: '8', rx: '2' }],
  ['path', { d: 'M5 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2h-2.4' }],
  ['path', { d: 'M8 18h.01' }],
];
