// The Lucide "table-of-contents" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTableOfContents: IconGlyph = [
  ['path', { d: 'M16 5H3' }],
  ['path', { d: 'M16 12H3' }],
  ['path', { d: 'M16 19H3' }],
  ['path', { d: 'M21 5h.01' }],
  ['path', { d: 'M21 12h.01' }],
  ['path', { d: 'M21 19h.01' }],
];
