// The Lucide "tablets" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTablets: IconGlyph = [
  ['circle', { cx: '7', cy: '7', r: '5' }],
  ['circle', { cx: '17', cy: '17', r: '5' }],
  ['path', { d: 'M12 17h10' }],
  ['path', { d: 'm3.46 10.54 7.08-7.08' }],
];
