// The Lucide "tally-1" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTally1: IconGlyph = [['path', { d: 'M4 4v16' }]];
