// The Lucide "tent-tree" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTentTree: IconGlyph = [
  ['circle', { cx: '4', cy: '4', r: '2' }],
  ['path', { d: 'm14 5 3-3 3 3' }],
  ['path', { d: 'm14 10 3-3 3 3' }],
  ['path', { d: 'M17 14V2' }],
  ['path', { d: 'M17 14H7l-5 8h20Z' }],
  ['path', { d: 'M8 14v8' }],
  ['path', { d: 'm9 14 5 8' }],
];
