// The Lucide "tent" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTent: IconGlyph = [
  ['path', { d: 'M3.5 21 14 3' }],
  ['path', { d: 'M20.5 21 10 3' }],
  ['path', { d: 'M15.5 21 12 15l-3.5 6' }],
  ['path', { d: 'M2 21h20' }],
];
