// The Lucide "terminal" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTerminal: IconGlyph = [
  ['path', { d: 'M12 19h8' }],
  ['path', { d: 'm4 17 6-6-6-6' }],
];
