// The Lucide "text-align-start" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTextAlignStart: IconGlyph = [
  ['path', { d: 'M21 5H3' }],
  ['path', { d: 'M15 12H3' }],
  ['path', { d: 'M17 19H3' }],
];
