// The Lucide "text-cursor" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTextCursor: IconGlyph = [
  ['path', { d: 'M17 22h-1a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4h1' }],
  ['path', { d: 'M7 22h1a4 4 0 0 0 4-4' }],
  ['path', { d: 'M7 2h1a4 4 0 0 1 4 4' }],
];
