// The Lucide "text-align-center" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTextAlignCenter: IconGlyph = [
  ['path', { d: 'M21 5H3' }],
  ['path', { d: 'M17 12H7' }],
  ['path', { d: 'M19 19H5' }],
];
