// The Lucide "text-align-end" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTextAlignEnd: IconGlyph = [
  ['path', { d: 'M21 5H3' }],
  ['path', { d: 'M21 12H9' }],
  ['path', { d: 'M21 19H7' }],
];
