// The Lucide "text-quote" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTextQuote: IconGlyph = [
  ['path', { d: 'M17 5H3' }],
  ['path', { d: 'M21 12H8' }],
  ['path', { d: 'M21 19H8' }],
  ['path', { d: 'M3 12v7' }],
];
