// The Lucide "toggle-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconToggleLeft: IconGlyph = [
  ['circle', { cx: '9', cy: '12', r: '3' }],
  ['rect', { width: '20', height: '14', x: '2', y: '5', rx: '7' }],
];
