// The Lucide "train-track" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTrainTrack: IconGlyph = [
  ['path', { d: 'M2 17 17 2' }],
  ['path', { d: 'm2 14 8 8' }],
  ['path', { d: 'm5 11 8 8' }],
  ['path', { d: 'm8 8 8 8' }],
  ['path', { d: 'm11 5 8 8' }],
  ['path', { d: 'm14 2 8 8' }],
  ['path', { d: 'M7 22 22 7' }],
];
