// The Lucide "trending-up-down" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTrendingUpDown: IconGlyph = [
  ['path', { d: 'M14.828 14.828 21 21' }],
  ['path', { d: 'M21 16v5h-5' }],
  ['path', { d: 'm21 3-9 9-4-4-6 6' }],
  ['path', { d: 'M21 8V3h-5' }],
];
