// The Lucide "turkish-lira" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTurkishLira: IconGlyph = [
  ['path', { d: 'M15 4 5 9' }],
  ['path', { d: 'm15 8.5-10 5' }],
  ['path', { d: 'M18 12a9 9 0 0 1-9 9V3' }],
];
