// The Lucide "turntable" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTurntable: IconGlyph = [
  ['path', { d: 'M10 12.01h.01' }],
  ['path', { d: 'M18 8v4a8 8 0 0 1-1.07 4' }],
  ['circle', { cx: '10', cy: '12', r: '4' }],
  ['rect', { x: '2', y: '4', width: '20', height: '16', rx: '2' }],
];
