// The Lucide "tv" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconTv: IconGlyph = [
  ['path', { d: 'm17 2-5 5-5-5' }],
  ['rect', { width: '20', height: '15', x: '2', y: '7', rx: '2' }],
];
