// The Lucide "umbrella" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUmbrella: IconGlyph = [
  ['path', { d: 'M12 13v7a2 2 0 0 0 4 0' }],
  ['path', { d: 'M12 2v2' }],
  ['path', { d: 'M20.992 13a1 1 0 0 0 .97-1.274 10.284 10.284 0 0 0-19.923 0A1 1 0 0 0 3 13z' }],
];
