// The Lucide "underline" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUnderline: IconGlyph = [
  ['path', { d: 'M6 4v6a6 6 0 0 0 12 0V4' }],
  ['line', { x1: '4', x2: '20', y1: '20', y2: '20' }],
];
