// The Lucide "undo-dot" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUndoDot: IconGlyph = [
  ['path', { d: 'M21 17a9 9 0 0 0-15-6.7L3 13' }],
  ['path', { d: 'M3 7v6h6' }],
  ['circle', { cx: '12', cy: '17', r: '1' }],
];
