// The Lucide "user-lock" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUserLock: IconGlyph = [
  ['path', { d: 'M19 16v-2a2 2 0 0 0-4 0v2' }],
  ['path', { d: 'M9.5 15H7a4 4 0 0 0-4 4v2' }],
  ['circle', { cx: '10', cy: '7', r: '4' }],
  ['rect', { x: '13', y: '16', width: '8', height: '5', rx: '.899' }],
];
