// The Lucide "user-round-x" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUserRoundX: IconGlyph = [
  ['path', { d: 'M2 21a8 8 0 0 1 11.873-7' }],
  ['circle', { cx: '10', cy: '8', r: '5' }],
  ['path', { d: 'm17 17 5 5' }],
  ['path', { d: 'm22 17-5 5' }],
];
