// The Lucide "user-search" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUserSearch: IconGlyph = [
  ['circle', { cx: '10', cy: '7', r: '4' }],
  ['path', { d: 'M10.3 15H7a4 4 0 0 0-4 4v2' }],
  ['circle', { cx: '17', cy: '17', r: '3' }],
  ['path', { d: 'm21 21-1.9-1.9' }],
];
