// The Lucide "user-round-arrow-left" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUserRoundArrowLeft: IconGlyph = [
  ['path', { d: 'm19 16-3 3' }],
  ['path', { d: 'M2 21a8 8 0 0 1 12.664-6.5' }],
  ['path', { d: 'M22 19h-6l3 3' }],
  ['circle', { cx: '10', cy: '8', r: '5' }],
];
