// The Lucide "users-round" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUsersRound: IconGlyph = [
  ['path', { d: 'M18 21a8 8 0 0 0-16 0' }],
  ['circle', { cx: '10', cy: '8', r: '5' }],
  ['path', { d: 'M22 20c0-3.37-2-6.5-4-8a5 5 0 0 0-.45-8.3' }],
];
