// The Lucide "utility-pole" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconUtilityPole: IconGlyph = [
  ['path', { d: 'M12 2v20' }],
  ['path', { d: 'M2 5h20' }],
  ['path', { d: 'M3 3v2' }],
  ['path', { d: 'M7 3v2' }],
  ['path', { d: 'M17 3v2' }],
  ['path', { d: 'M21 3v2' }],
  ['path', { d: 'm19 5-7 7-7-7' }],
];
