// The Lucide "venus-and-mars" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconVenusAndMars: IconGlyph = [
  ['path', { d: 'M10 20h4' }],
  ['path', { d: 'M12 16v6' }],
  ['path', { d: 'M17 2h4v4' }],
  ['path', { d: 'm21 2-5.46 5.46' }],
  ['circle', { cx: '12', cy: '11', r: '5' }],
];
