// The Lucide "vibrate" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconVibrate: IconGlyph = [
  ['path', { d: 'm2 8 2 2-2 2 2 2-2 2' }],
  ['path', { d: 'm22 8-2 2 2 2-2 2 2 2' }],
  ['rect', { width: '8', height: '14', x: '8', y: '5', rx: '1' }],
];
