// The Lucide "voicemail" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconVoicemail: IconGlyph = [
  ['circle', { cx: '6', cy: '12', r: '4' }],
  ['circle', { cx: '18', cy: '12', r: '4' }],
  ['line', { x1: '6', x2: '18', y1: '16', y2: '16' }],
];
