// The Lucide "wallpaper" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWallpaper: IconGlyph = [
  ['path', { d: 'M12 17v4' }],
  ['path', { d: 'M8 21h8' }],
  ['path', { d: 'm9 17 6.1-6.1a2 2 0 0 1 2.81.01L22 15' }],
  ['circle', { cx: '8', cy: '9', r: '2' }],
  ['rect', { x: '2', y: '3', width: '20', height: '14', rx: '2' }],
];
