// The Lucide "waves-vertical" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWavesVertical: IconGlyph = [
  ['path', { d: 'M12 2q2 2.5 0 5t0 5 0 5 0 5' }],
  ['path', { d: 'M19 2q2 2.5 0 5t0 5 0 5 0 5' }],
  ['path', { d: 'M5 2q2 2.5 0 5t0 5 0 5 0 5' }],
];
