// The Lucide "whole-word" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWholeWord: IconGlyph = [
  ['circle', { cx: '7', cy: '12', r: '3' }],
  ['path', { d: 'M10 9v6' }],
  ['circle', { cx: '17', cy: '12', r: '3' }],
  ['path', { d: 'M14 7v8' }],
  ['path', { d: 'M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1' }],
];
