// The Lucide "wifi-zero" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWifiZero: IconGlyph = [['path', { d: 'M12 20h.01' }]];
