// The Lucide "wifi-low" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWifiLow: IconGlyph = [
  ['path', { d: 'M12 20h.01' }],
  ['path', { d: 'M8.5 16.429a5 5 0 0 1 7 0' }],
];
