// The Lucide "wifi-sync" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWifiSync: IconGlyph = [
  ['path', { d: 'M11.965 10.105v4L13.5 12.5a5 5 0 0 1 8 1.5' }],
  ['path', { d: 'M11.965 14.105h4' }],
  ['path', { d: 'M17.965 18.105h4L20.43 19.71a5 5 0 0 1-8-1.5' }],
  ['path', { d: 'M2 8.82a15 15 0 0 1 20 0' }],
  ['path', { d: 'M21.965 22.105v-4' }],
  ['path', { d: 'M5 12.86a10 10 0 0 1 3-2.032' }],
  ['path', { d: 'M8.5 16.429h.01' }],
];
