// The Lucide "wind-arrow-down" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWindArrowDown: IconGlyph = [
  ['path', { d: 'M10 2v8' }],
  ['path', { d: 'M12.8 21.6A2 2 0 1 0 14 18H2' }],
  ['path', { d: 'M17.5 10a2.5 2.5 0 1 1 2 4H2' }],
  ['path', { d: 'm6 6 4 4 4-4' }],
];
