// The Lucide "wind" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconWind: IconGlyph = [
  ['path', { d: 'M12.8 19.6A2 2 0 1 0 14 16H2' }],
  ['path', { d: 'M17.5 8a2.5 2.5 0 1 1 2 4H2' }],
  ['path', { d: 'M9.8 4.4A2 2 0 1 1 11 8H2' }],
];
