// The Lucide "x-line-top" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconXLineTop: IconGlyph = [
  ['path', { d: 'M18 4H6' }],
  ['path', { d: 'M18 8 6 20' }],
  ['path', { d: 'm6 8 12 12' }],
];
