// The Lucide "zodiac-cancer" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconZodiacCancer: IconGlyph = [
  ['path', { d: 'M21 14.5A9 6.5 0 0 1 5.5 19' }],
  ['path', { d: 'M3 9.5A9 6.5 0 0 1 18.5 5' }],
  ['circle', { cx: '17.5', cy: '14.5', r: '3.5' }],
  ['circle', { cx: '6.5', cy: '9.5', r: '3.5' }],
];
