// The Lucide "zodiac-taurus" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconZodiacTaurus: IconGlyph = [
  ['circle', { cx: '12', cy: '15', r: '6' }],
  ['path', { d: 'M18 3A6 6 0 0 1 6 3' }],
];
