// The Lucide "zodiac-capricorn" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconZodiacCapricorn: IconGlyph = [
  ['path', { d: 'M11 21a3 3 0 0 0 3-3V6.5a1 1 0 0 0-7 0' }],
  ['path', { d: 'M7 19V6a3 3 0 0 0-3-3h0' }],
  ['circle', { cx: '17', cy: '17', r: '3' }],
];
