// The Lucide "zodiac-sagittarius" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconZodiacSagittarius: IconGlyph = [
  ['path', { d: 'M15 3h6v6' }],
  ['path', { d: 'M21 3 3 21' }],
  ['path', { d: 'm9 9 6 6' }],
];
