// The Lucide "zodiac-ophiuchus" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconZodiacOphiuchus: IconGlyph = [
  ['path', { d: 'M3 10A6.06 6.06 0 0 1 12 10 A6.06 6.06 0 0 0 21 10' }],
  ['path', { d: 'M6 3v12a6 6 0 0 0 12 0V3' }],
];
