// The Lucide "zodiac-pisces" glyph as data. GENERATED by src/icons/build-icons.ts — do not edit.
// Icon artwork © Lucide contributors, ISC (see src/icons/LICENSE.lucide).

import type { IconGlyph } from '../../components/icon-glyph';

export const iconZodiacPisces: IconGlyph = [
  ['path', { d: 'M19 21a15 15 0 0 1 0-18' }],
  ['path', { d: 'M20 12H4' }],
  ['path', { d: 'M5 3a15 15 0 0 1 0 18' }],
];
