-- 20260825142934_carry_declared_invariants_and_defaults
-- GENERATED by `x db gen` from the app's entities — do not edit.
-- Editing an applied migration changes its checksum: X_MIGRATION_CONFLICT on the next apply.

alter table "comments" add constraint "comments_comment_body_present_check" check (char_length(btrim(body)) >= 1);
alter table "media" add constraint "media_media_bytes_positive_check" check (bytes >= 1);
alter table "messages" add constraint "messages_message_body_present_check" check (char_length(btrim(body)) >= 1);
alter table "posts" add constraint "posts_post_body_present_check" check (char_length(btrim(body)) >= 1);
alter table "posts" add constraint "posts_post_like_count_non_negative_check" check (like_count >= 0);
alter table "posts" add constraint "posts_post_comment_count_non_negative_check" check (comment_count >= 0);
alter table "posts" add constraint "posts_post_media_count_non_negative_check" check (media_count >= 0);
alter table "users" add constraint "users_user_email_shape_check" check (position('@' in email) > 0);
alter table "users" add constraint "users_user_display_name_present_check" check (char_length(btrim(display_name)) >= 1);

-- down
alter table "users" drop constraint "users_user_display_name_present_check";
alter table "users" drop constraint "users_user_email_shape_check";
alter table "posts" drop constraint "posts_post_media_count_non_negative_check";
alter table "posts" drop constraint "posts_post_comment_count_non_negative_check";
alter table "posts" drop constraint "posts_post_like_count_non_negative_check";
alter table "posts" drop constraint "posts_post_body_present_check";
alter table "messages" drop constraint "messages_message_body_present_check";
alter table "media" drop constraint "media_media_bytes_positive_check";
alter table "comments" drop constraint "comments_comment_body_present_check";
