-- 20260817122509_initial_schema
-- GENERATED by `x db gen` from the app's entities — do not edit.
-- Editing an applied migration changes its checksum: X_MIGRATION_CONFLICT on the next apply.
--
-- ONE hand edit, and only this one: the create-table blocks (and the drops below) were reordered so
-- that a table is created before the table whose foreign key references it. `generateMigration`
-- (packages/db/src/generate.ts:383) emits them in entity-registration order, which put
-- `blocks references users` first and made this file fail on `relation "users" does not exist` —
-- proven, and pinned by `packages/db/src/migrations.test.ts`, which applies every committed
-- migration to an empty PGlite. Nothing else was touched: same statements, same checksum inputs,
-- and this migration has never been applied anywhere. The generator needs a topological sort.

create table "users" (
  "id" uuid default gen_random_uuid() not null,
  "handle" text not null unique check (char_length(handle) <= 30),
  "email" text not null unique check (char_length(email) <= 254),
  "display_name" text not null check (char_length(display_name) <= 80),
  "bio" text check (char_length(bio) <= 300),
  "avatar_key" text check (char_length(avatar_key) <= 512),
  "role" text not null check (role in ('member', 'admin')),
  "tz" text not null check (tz in ('UTC', 'America/New_York', 'Europe/Madrid', 'Asia/Tokyo', 'Pacific/Auckland')),
  "locale" text not null check (locale in ('en', 'es')),
  "deleted_at" timestamptz,
  "suspended" boolean not null,
  "created_at" timestamptz default now() not null,
  "updated_at" timestamptz default now() not null,
  primary key ("id")
);
create index "users_created_at_idx" on "users" ("created_at" desc);
create table "conversations" (
  "id" uuid default gen_random_uuid() not null,
  "kind" text not null check (kind in ('direct', 'group')),
  "title" text check (char_length(title) <= 120),
  "created_at" timestamptz default now() not null,
  primary key ("id")
);
create table "posts" (
  "id" uuid default gen_random_uuid() not null,
  "author_id" uuid not null references "users" ("id"),
  "body" text not null check (char_length(body) <= 5000),
  "audience" text not null check (audience in ('public', 'friends', 'private')),
  "like_count" integer not null,
  "comment_count" integer not null,
  "media_count" integer not null,
  "published_at" timestamptz default now() not null,
  "deleted_at" timestamptz,
  "created_at" timestamptz default now() not null,
  "updated_at" timestamptz default now() not null,
  primary key ("id")
);
create index "posts_author_id_idx" on "posts" ("author_id");
create index "posts_author_id_published_at_idx" on "posts" ("author_id" desc, "published_at" desc);
create index "posts_published_at_idx" on "posts" ("published_at" desc) where (audience = 'public');
create table "blocks" (
  "blocker_id" uuid not null references "users" ("id"),
  "blocked_id" uuid not null references "users" ("id"),
  "created_at" timestamptz default now() not null,
  primary key ("blocker_id", "blocked_id")
);
create index "blocks_blocker_id_idx" on "blocks" ("blocker_id");
create index "blocks_blocked_id_idx" on "blocks" ("blocked_id");
create table "comments" (
  "id" uuid default gen_random_uuid() not null,
  "post_id" uuid not null references "posts" ("id"),
  "author_id" uuid not null references "users" ("id"),
  "body" text not null check (char_length(body) <= 5000),
  "deleted_at" timestamptz,
  "created_at" timestamptz default now() not null,
  primary key ("id")
);
create index "comments_post_id_idx" on "comments" ("post_id");
create index "comments_author_id_idx" on "comments" ("author_id");
create index "comments_post_id_created_at_id_idx" on "comments" ("post_id", "created_at", "id");
create table "credentials" (
  "user_id" uuid default gen_random_uuid() not null references "users" ("id"),
  "password_hash" text not null check (char_length(password_hash) <= 255),
  "updated_at" timestamptz default now() not null,
  primary key ("user_id")
);
create index "credentials_user_id_idx" on "credentials" ("user_id");
create table "friendships" (
  "requester_id" uuid not null references "users" ("id"),
  "addressee_id" uuid not null references "users" ("id"),
  "status" text not null check (status in ('pending', 'accepted', 'declined')),
  "responded_at" timestamptz,
  "created_at" timestamptz default now() not null,
  primary key ("requester_id", "addressee_id")
);
create index "friendships_requester_id_idx" on "friendships" ("requester_id");
create index "friendships_addressee_id_idx" on "friendships" ("addressee_id");
create index "friendships_addressee_id_status_idx" on "friendships" ("addressee_id", "status");
create table "likes" (
  "post_id" uuid not null references "posts" ("id"),
  "user_id" uuid not null references "users" ("id"),
  "created_at" timestamptz default now() not null,
  primary key ("post_id", "user_id")
);
create index "likes_post_id_idx" on "likes" ("post_id");
create index "likes_user_id_idx" on "likes" ("user_id");
create index "likes_user_id_created_at_idx" on "likes" ("user_id" desc, "created_at" desc);
create table "media" (
  "id" uuid default gen_random_uuid() not null,
  "post_id" uuid references "posts" ("id"),
  "owner_id" uuid not null references "users" ("id"),
  "key" text not null unique check (char_length(key) <= 512),
  "kind" text not null check (kind in ('image', 'video')),
  "content_type" text not null check (char_length(content_type) <= 128),
  "bytes" integer not null,
  "width" integer,
  "height" integer,
  "state" text not null check (state in ('pending', 'attached', 'orphan')),
  "created_at" timestamptz default now() not null,
  primary key ("id")
);
create index "media_post_id_idx" on "media" ("post_id");
create index "media_owner_id_idx" on "media" ("owner_id");
create index "media_created_at_idx" on "media" ("created_at") where (state = 'pending');
create table "messages" (
  "id" uuid default gen_random_uuid() not null,
  "conversation_id" uuid not null references "conversations" ("id"),
  "author_id" uuid not null references "users" ("id"),
  "body" text not null check (char_length(body) <= 5000),
  "created_at" timestamptz default now() not null,
  primary key ("id")
);
create index "messages_conversation_id_idx" on "messages" ("conversation_id");
create index "messages_author_id_idx" on "messages" ("author_id");
create index "messages_conversation_id_created_at_id_idx" on "messages" ("conversation_id" desc, "created_at" desc, "id" desc);
create table "notifications" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null references "users" ("id"),
  "kind" text not null check (kind in ('friend-request', 'friend-accepted', 'post-liked', 'post-commented', 'message')),
  "actor_id" uuid not null references "users" ("id"),
  "subject_id" uuid,
  "read_at" timestamptz,
  "created_at" timestamptz default now() not null,
  primary key ("id")
);
create index "notifications_user_id_idx" on "notifications" ("user_id");
create index "notifications_actor_id_idx" on "notifications" ("actor_id");
create index "notifications_user_id_created_at_idx" on "notifications" ("user_id" desc, "created_at" desc);
create table "participants" (
  "conversation_id" uuid not null references "conversations" ("id"),
  "user_id" uuid not null references "users" ("id"),
  "last_read_at" timestamptz,
  "joined_at" timestamptz default now() not null,
  primary key ("conversation_id", "user_id")
);
create index "participants_conversation_id_idx" on "participants" ("conversation_id");
create index "participants_user_id_idx" on "participants" ("user_id");
create table "sessions" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null references "users" ("id"),
  "token_hash" text not null unique check (char_length(token_hash) <= 128),
  "expires_at" timestamptz not null,
  "created_at" timestamptz default now() not null,
  primary key ("id")
);
create index "sessions_user_id_idx" on "sessions" ("user_id");
create index "sessions_expires_at_idx" on "sessions" ("expires_at");

-- down
drop table "sessions";
drop table "participants";
drop table "notifications";
drop table "messages";
drop table "media";
drop table "likes";
drop table "friendships";
drop table "credentials";
drop table "comments";
drop table "blocks";
drop table "posts";
drop table "conversations";
drop table "users";
