-- 20261009144006_credentials_and_sessions_move_to_the_framework_auth_tables
-- GENERATED by `x db gen` from the app's entities — do not edit.
-- Editing an applied migration changes its checksum: X_MIGRATION_CONFLICT on the next apply.
-- destructive: true
-- ungeneratable: 1

-- Carried by hand, above the generated drops: every password a visitor set on the deployed demo
-- moves into `@ultimat3/auth`'s `x_users`, under the same id as its `users` row — the link
-- `apps/web/app/auth/auth.ts` signs in through. The framework schema is applied before an app's
-- migrations on every boot path (`runMigrations` starts the queue first), so `x_users` exists; the
-- guard keeps a database built from these files alone, as `postgres.test.ts` builds one, applying.
-- Sessions are not carried: their tokens were the app's own format, and a visitor signs in again.
do $$
begin
  if to_regclass('x_users') is not null then
    insert into x_users (id, email, password_hash, created_at)
    select u.id, lower(trim(u.email)), c.password_hash, u.created_at
      from users u
      join credentials c on c.user_id = u.id
    on conflict do nothing;
  end if;
end
$$;

drop table "credentials";
drop table "sessions";

-- down
-- "sessions" cannot be restored; recover it from a backup
-- "credentials" cannot be restored; recover it from a backup
