-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

alter table "x_sessions" add constraint "x_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES x_users(id) ON DELETE CASCADE;
