-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "credentials" (
  "user_id" uuid default gen_random_uuid() not null,
  "password_hash" text not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "credentials_pkey" PRIMARY KEY (user_id),
  constraint "credentials_password_hash_check" CHECK ((char_length(password_hash) <= 255))
);
