-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "friendships" (
  "requester_id" uuid not null,
  "addressee_id" uuid not null,
  "status" text not null,
  "responded_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  constraint "friendships_pkey" PRIMARY KEY (requester_id, addressee_id),
  constraint "friendships_friendship_responded_coherent_check" CHECK (((status = 'pending'::text) = (responded_at IS NULL))),
  constraint "friendships_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])))
);
