-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "likes" (
  "post_id" uuid not null,
  "user_id" uuid not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "likes_pkey" PRIMARY KEY (post_id, user_id)
);
