-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "notifications" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "kind" text not null,
  "actor_id" uuid not null,
  "subject_id" uuid,
  "read_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  constraint "notifications_pkey" PRIMARY KEY (id),
  constraint "notifications_kind_check" CHECK ((kind = ANY (ARRAY['friend-request'::text, 'friend-accepted'::text, 'post-liked'::text, 'post-commented'::text, 'message'::text])))
);

alter table "notifications" replica identity full;
