-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "participants" (
  "conversation_id" uuid not null,
  "user_id" uuid not null,
  "last_read_at" timestamp with time zone,
  "joined_at" timestamp with time zone default now() not null,
  constraint "participants_pkey" PRIMARY KEY (conversation_id, user_id)
);
