-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "sessions" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "token_hash" text not null,
  "expires_at" timestamp with time zone not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "sessions_pkey" PRIMARY KEY (id),
  constraint "sessions_token_hash_key" UNIQUE (token_hash),
  constraint "sessions_token_hash_check" CHECK ((char_length(token_hash) <= 128))
);
