// `x db gen`, on the framework's own engine. The app's registered entities diffed against what the
// migration files already declare, written as one reversible `.sql` plus the two sidecars the gate
// reads back — the snapshot the next generation diffs against, and the schema hash `drift` checks.

// `node:path` — Bun ships no path joiner of its own, and these paths are built, not opened.
import { join } from 'node:path';
import type { GeneratedMigration } from '@ultimat3/db';
import {
  DESTRUCTIVE_MARKER,
  declaredSchema,
  generateMigration,
  migrationSnapshotMissing,
} from '@ultimat3/db';
import { describeEntities } from '@ultimat3/entity';
import { loadApp } from './app-load';
import { writeSchemaHash } from './drift';
import { hashFileName, MIGRATIONS_DIR, readMigrations, snapshotFileName } from './migrations';
import type { Finding } from './output';

export interface GenerateMigrationOptions {
  readonly name: string;
  /** `x db gen "…" --allow-destructive`. A DROP whose `down` cannot restore the rows. */
  readonly allowDestructive?: boolean | undefined;
}

export interface GeneratedFiles {
  /** Absent when the entities and the migrations already agree — nothing was written. */
  readonly migration?: GeneratedMigration | undefined;
  /** App-root-relative paths written, in write order. Empty when there was nothing to write. */
  readonly files: readonly string[];
  readonly schemaHash?: string | undefined;
  /** Modules that would not load. Non-empty means nothing was generated. */
  readonly findings: readonly Finding[];
}

/**
 * The header every generated migration carries. It names the id rather than interpolating the
 * caller's own message: a `name` is free text from argv, and a newline in it would end the comment
 * and turn prose into SQL.
 *
 * A destructive `up` carries the marker `x verify` demands, written here rather than hand-added
 * later: the marker is part of the SQL the checksum covers, so a migration that earns it after it
 * has been applied is an edited migration and `X_MIGRATION_CONFLICT` — correctly — says so.
 */
export function migrationSql(migration: GeneratedMigration): string {
  return [
    `-- ${migration.id}`,
    "-- GENERATED by `x db gen` from the app's entities — do not edit.",
    '-- Editing an applied migration changes its checksum: X_MIGRATION_CONFLICT on the next apply.',
    ...(migration.destructive ? [DESTRUCTIVE_MARKER] : []),
    '',
    migration.up,
    '',
    '-- down',
    migration.down,
    '',
  ].join('\n');
}

/**
 * Generation reads source and writes files; it never opens a database. The previous migration's
 * snapshot is what it diffs against (`declaredSchema`), so `x db gen` answers the same in CI, on a
 * laptop with no Postgres running, and against a database three migrations behind.
 *
 * An app that would not load generates nothing. `describeEntities()` is the registry a failed
 * import leaves short, and a diff against a short registry is a migration that drops the tables
 * whose module happened to throw — the one destructive edit no `--allow-destructive` was asked for.
 */
export async function generateAppMigration(
  root: string,
  options: GenerateMigrationOptions,
): Promise<GeneratedFiles> {
  const app = await loadApp(root);
  if (app.findings.length > 0) return { files: [], findings: app.findings };

  const migrations = await readMigrations(root);
  const current = declaredSchema(migrations);
  // Refused, never defaulted to the empty schema: with nothing to diff against, every table the
  // database already holds looks new and the generated `up` is `create table` for all of them.
  if (current === undefined) {
    const newest = migrations[migrations.length - 1];
    const id = newest?.id ?? '';
    throw migrationSnapshotMissing(id, join(MIGRATIONS_DIR, snapshotFileName(id)));
  }

  const migration = generateMigration({
    entities: describeEntities(),
    current,
    name: options.name,
    ...(options.allowDestructive === true ? { allowDestructive: true } : {}),
  });
  // An empty diff writes nothing. A migration with no statement still takes a ledger row, a
  // checksum and a place in the apply order — a permanent record that nothing changed.
  if (migration.up.trim().length === 0) return { files: [], findings: [] };

  const dir = join(root, MIGRATIONS_DIR);
  const sql = `${migration.id}.sql`;
  const snapshot = snapshotFileName(migration.id);
  await Bun.write(join(dir, sql), migrationSql(migration));
  await Bun.write(join(dir, snapshot), `${JSON.stringify(migration.snapshot, null, 2)}\n`);
  const schemaHash = await writeSchemaHash(root, migration.id);

  return {
    migration,
    schemaHash,
    files: [sql, snapshot, hashFileName(migration.id)].map((file) => `${MIGRATIONS_DIR}/${file}`),
    findings: [],
  };
}
