-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_admin_audit" (
  "id" uuid not null,
  "at" timestamp with time zone not null,
  "request_id" text not null,
  "actor_id" text not null,
  "actor_roles" jsonb not null,
  "org_id" text,
  "operation" text not null,
  "kind" text not null,
  "entity" text not null,
  "entity_id" text,
  "permission" text not null,
  "outcome" text not null,
  "reason" text not null,
  "diff" jsonb not null,
  "recorded_at" timestamp with time zone default now() not null,
  constraint "x_admin_audit_pkey" PRIMARY KEY (id)
);
