-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_audit" (
  "id" uuid not null,
  "at" timestamp with time zone,
  "action" text not null,
  "mutator" boolean not null,
  "surface" text not null,
  "outcome" text not null,
  "replayed" boolean not null,
  "idempotency_key" text,
  "failure_code" text,
  "actor_id" text not null,
  "actor_kind" text not null,
  "org_id" text,
  "on_behalf_of_id" text,
  "on_behalf_of_kind" text,
  "request_id" text not null,
  "trace_id" text not null,
  "locale" text not null,
  "tz" text not null,
  "build_id" text not null,
  "role" text not null,
  "input" jsonb,
  "recorded_at" timestamp with time zone default now() not null,
  "primitive" text default 'action'::text not null,
  constraint "x_audit_pkey" PRIMARY KEY (id)
);
