-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_idempotency" (
  "key" text not null,
  "id" uuid not null,
  "request_hash" text not null,
  "status" text default 'in-flight'::text not null,
  "value" jsonb,
  "failure" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "tx_bound" boolean default false not null,
  "redacted" boolean default false not null,
  constraint "x_idempotency_pkey" PRIMARY KEY (key)
);
