-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_job_pauses" (
  "kind" text not null,
  "name" text not null,
  "paused_at" timestamp with time zone default now() not null,
  constraint "x_job_pauses_pkey" PRIMARY KEY (kind, name)
);
