-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_job_events" (
  "id" uuid not null,
  "name" text not null,
  "payload" jsonb not null,
  "correlation_key" text,
  "published_at" timestamp with time zone default now() not null,
  "expires_at" timestamp with time zone not null,
  constraint "x_job_events_pkey" PRIMARY KEY (id)
);
