-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_migrations" (
  "id" text not null,
  "name" text not null,
  "checksum" text not null,
  "applied_at" timestamp with time zone default now() not null,
  "app_version" text not null,
  "duration_ms" integer not null,
  constraint "x_migrations_pkey" PRIMARY KEY (id)
);
