-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_notify_inbox" (
  "id" uuid not null,
  "recipient" text not null,
  "notifier" text not null,
  "key" text not null,
  "params" jsonb not null,
  "created_at" timestamp with time zone default now() not null,
  "seen_at" timestamp with time zone,
  "read_at" timestamp with time zone,
  constraint "x_notify_inbox_pkey" PRIMARY KEY (id),
  constraint "x_notify_inbox_recipient_notifier_key_key" UNIQUE (recipient, notifier, key)
);
