-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "x_sessions" (
  "id" text not null,
  "user_id" uuid not null,
  "token_hash" text not null,
  "created_at" timestamp with time zone default now() not null,
  "absolute_expires_at" timestamp with time zone not null,
  "last_seen_at" timestamp with time zone default now() not null,
  "ip" text,
  "user_agent" text,
  "mfa_satisfied" boolean default false not null,
  constraint "x_sessions_pkey" PRIMARY KEY (id)
);
