// The ratchet under `scripts/wiki-fences.ts`: every fenced `ts`/`tsx` example on a `wiki/` page
// that does not typecheck today, keyed by FENCE — `<page>: <its first code line>` — with how many
// fences of that page open with that line. A row may FALL and may never rise — a new example must
// compile from the day it is written, and the ones that do not get retired over time.
//
// Measured when this shipped (2026-10-06): 182 failing across 45 pages. Most are the
// fragments `scripts/readme-fences-backlog.ts` describes for package READMEs — an identifier the
// prose around the block defines, an app-level import (`@app/db`, `./entity`) that resolves in
// an app and not here, a signature with its arguments elided. Keyed on the first code line for
// that file's reason: it moves only when the example does, where a line number moves on every
// paragraph edit; a per-page count let a fixed example be swapped for a new broken one unseen.
//
// why: the table is new in sweep 11 and opens with the wiki's whole measured debt at once — no
// wiki fence was ever compiled before it, so every count is a first measurement, not a raise.
// why: re-keyed per fence in plan 101 sweep 11c — the same 182 failing fences at 178 sites;
// `pin-raises` reads a wholly re-keyed table against its old total.
//
// Shrink it with `bun run scripts/wiki-fences.ts --pin`, which lowers a row and refuses to
// raise one. Adding or raising a row is a hand edit, on purpose, in a review.

export const WIKI_FENCE_BACKLOG: Readonly<Record<string, number>> = {
  'Actions: // contract test — generated with the action': 1,
  'Actions: export const likePost = mutator({': 1,
  'Actions: export const publishPost = action({': 1,
  'Admin-Dashboard: // apps/admin/app/admin/admin.ts — the whole dashboard': 1,
  "Admin-Dashboard: mcp: { expose: true, description: 'Publish a draft post' },": 1,
  'Admin-Dashboard: resources: { posts: { count: true } },': 1,
  'Agents: budget: {': 1,
  'Agents: const result = await triageBacklog({ orderIds }, { ctx });': 1,
  "Agents: import { agentJob } from '@ultimat3/ai';": 1,
  "Agents: import { database, entity, text, timestamp, uuid } from '@ultimat3/entity';": 1,
  "Agents: import { t } from '@ultimat3/action';": 2,
  'Agents: onTurn: ({ turn, maxTurns, model, toolCalls, stopReason, usage, cost }) => {': 1,
  // why: re-keyed, not raised — the 25.0.0 rename changed this fence's text; same site, same count
  "Auth: import { defineAuth, login, oauthLogin, postgresAuthAdapter } from '@ultimat3/auth';": 1,
  'Batching-And-Preloading: await db.tags.insertAll(names.map((name) => ({ orgId, name })));         // one statement, n rows': 1,
  "Batching-And-Preloading: await using batches = db.posts.where({ orgId }).preload('author').inBatches(500);": 1,
  'Batching-And-Preloading: const page = await db.posts.findMany({ orgId });': 1,
  'Batching-And-Preloading: export const db = database({ orgs, posts, members });': 1,
  'Building-Your-Own-Base: // apps/web/app/invoices/entity.ts': 1,
  'CLI-Reference: // app.config.ts': 1,
  'Caching-And-Invalidation: // action': 1,
  'Caching-And-Invalidation: export const summarize = llm({': 1,
  'Caching-And-Invalidation: export const tag = tags({': 1,
  'Client-Data: // app/posts/actions.ts': 1,
  'Client-Data: // app/posts/queries.ts': 1,
  'Client-Data: // app/posts/rename.island.tsx': 1,
  'Client-Data: // shared/browser-client.ts — type-only import of the api, so no server code reaches the island': 1,
  'Client-Navigation: // app.config.ts': 1,
  "Client-Navigation: export const config = defineRoute({ render: 'ssr', …, navigation: 'prefetch' });": 1,
  "Client-Navigation: navigation: { speculation: { prefetch: 'moderate', exclude: ['/blog/borrador-*'] } },": 1,
  'Configuration: // app.config.ts': 1,
  "Configuration: defineStorage({ disks: { uploads: localDriver({ root: '.storage/uploads' }) } });": 1,
  'Configuration: export const config = defineConfig({': 1,
  "Configuration: import { isLocal, isProduction, resolveEnvironment, tryResolveEnvironment } from '@ultimat3/core';": 1,
  "Configuration: import { renderEnvExample, ENV_EXAMPLE_PATH } from '@ultimat3/core';": 1,
  "Configuration: import { secret, revealSecret, isSecret } from '@ultimat3/core';": 1,
  'Configuration: islands: { sharedChunks: true },': 1,
  'Configuration: mail: { retainMime: { maxBytes: 262_144 } },': 1,
  "Configuration: navigation: { client: ['app'], speculation: { prefetch: 'moderate', exclude: [] } },": 1,
  'Configuration: pwa: {': 1,
  "Configuration: site: { origin: 'https://www.example.com' },": 1,
  'Contributing: throw new UltimateError({': 1,
  'Entities-And-Migrations: // One `select … where "id" in ($1, $2, $3, …)`, not one statement per post.': 1,
  'Entities-And-Migrations: // One statement for all of `ids`, not one `select count(*)` per post.': 1,
  'Entities-And-Migrations: // One statement per batch, one page of rows in memory at a time.': 1,
  'Entities-And-Migrations: // apps/web/app/connection/backfills/seal-connection-passwords.ts — a backfill IS a job: register': 1,
  'Entities-And-Migrations: // apps/web/app/widget/repo.ts — as `x g entity widget` writes it': 1,
  'Entities-And-Migrations: // packages/db/src/client.ts — the handle. `x g entity` adds the import and the line.': 1,
  'Entities-And-Migrations: await db.tags.insertAll(names.map((name) => ({ orgId, name })));   // one statement, n rows': 1,
  'Entities-And-Migrations: await using batches = db.posts.where({ orgId }).after(checkpoint).inBatches(500);': 1,
  'Entities-And-Migrations: const page = await db.posts.findMany({ orgId });': 1,
  "Entities-And-Migrations: embed: { field: 'body', model: 'text-embedding-3-large' },": 1,
  "Entities-And-Migrations: expect(row).toEqualRow({ id, label: 'primary', password: 'hunter2' }); // every own property": 1,
  "Entities-And-Migrations: export const accounts = entity('account', {": 1,
  "Entities-And-Migrations: export const connections = entity('connections', {": 1,
  'Entities-And-Migrations: export const db = database({ orgs, posts, members });': 1,
  "Entities-And-Migrations: export const dev = defineSeed('dev', async ({ insert, upsert, exists, id }) => {": 1,
  "Entities-And-Migrations: export const posts = entity('posts', {": 1,
  "Feature-Flags: import { defineFlag, isEnabled } from '@ultimat3/flags';": 1,
  'Getting-Started: // apps/web/api/index.ts': 1,
  'Getting-Started: // apps/web/app/posts/ui/publish-button.tsx': 1,
  'Getting-Started: // apps/web/shared/client.ts': 1,
  'Getting-Started: export const publishPost = action({': 1,
  'Jobs-And-Workflows: // job': 1,
  'Jobs-And-Workflows: // job test — the step guarantee, not the happy path': 1,
  'Jobs-And-Workflows: async handle({ input, ctx }) {': 1,
  'Jobs-And-Workflows: export const syncAccount = job({': 1,
  'Jobs-And-Workflows: export const syncCrm = job({': 1,
  'Jobs-And-Workflows: export interface JobDriver {': 1,
  'Jobs-And-Workflows: idempotencyKey: ({ orgId }) => `onboard:${orgId}`,   // REQUIRED by the type': 1,
  "Jobs-And-Workflows: import { memoryWebhookLedger, webhook } from '@ultimat3/jobs';": 1,
  'Jobs-And-Workflows: run: async ({ input, ctx, step }) => {': 1,
  'MCP-And-AI: // apps/web/mcp.ts': 1,
  'MCP-And-AI: class RefundWindowError extends UltimateError {': 1,
  'MCP-And-AI: export const mcp = defineAppMcp({': 1,
  'MCP-And-AI: export const summarize = llm({': 1,
  "MCP-And-AI: import { assertMcpSurfaceBudget } from '@ultimat3/mcp';": 1,
  'MCP-And-AI: mcp: {': 1,
  "MCP-And-AI: mcp: { expose: true, description: 'Publish a draft post' },": 1,
  'Mail: // app.config.ts': 1,
  "Mail: import { blocks, defineMail, send, t } from '@ultimat3/mail';": 1,
  "Migrating-An-Existing-App: import { backfill } from '@ultimat3/jobs';": 1,
  'Migrations-And-Backfills: backfill<Row>({': 1,
  'Migrations-And-Backfills: const first = await normalizePostTitles.enqueue({});': 1,
  'Migrations-And-Backfills: export const normalizePostTitles = backfill({': 1,
  'Money: export const summarize = llm({': 1,
  "Money: money(1999, 'USD');            // $19.99      — no scale key, the currency's own minor unit": 1,
  "Money: total: money({ columns: { minor: 'amount_cents', currency: 'currency', scale: null } }),": 1,
  'N-Plus-One-Detection: // naive: one statement per row': 1,
  'N-Plus-One-Detection: // one indexed lookup per search field beats one unindexed OR across all of them': 1,
  'N-Plus-One-Detection: // one statement for the page': 1,
  "N-Plus-One-Detection: test('the feed reads its authors once', async ({ statements }) => {": 1,
  "Notify: import { inAppChannel, mailChannel, notifier, t } from '@ultimat3/notify';": 1,
  "Observability: import { collectMetrics, configureMetrics, exportMetrics, startMetricExport } from '@ultimat3/core';": 1,
  'PWA-And-Offline: // app.config.ts — every member optional; text is a string or one per locale': 1,
  'PWA-And-Offline: // app.config.ts — omitting `offline.fallback` is a compile error': 1,
  'PWA-And-Offline: // app.config.ts: the two capabilities an app can switch on, both booleans': 1,
  'PWA-And-Offline: export const config = defineRoute({': 1,
  'Policies-And-Authz: // contract test — generated as a scaffold with the action': 1,
  "Policies-And-Authz: policy: can('post:publish', ({ input, actor }) => ownsPost(actor, input.postId))": 1,
  "Queries-And-Live-Queries: // apps/web/shared/client.ts — the app's one place for both": 1,
  'Queries-And-Live-Queries: // query': 1,
  'Queries-And-Live-Queries: export const postById = query({': 1,
  'Realtime: // app/feed/channels.ts — the SERVER half, on the same ref. Registers on import.': 1,
  'Realtime: // in an island: the ref, never the server half (which would bundle the entity and its driver)': 1,
  'Realtime: // mutator (action + optimistic local twin)': 1,
  'Resource-Management: using connection = await client.reserve();': 1,
  'Routes-And-Render-Modes: <Image src={post.cover} alt={post.title} sizes="(max-width: 700px) 100vw, 700px" priority />': 1,
  'Routes-And-Render-Modes: export const config = defineRoute({': 2,
  'Routes-And-Render-Modes: export default function Dashboard() {': 1,
  "Routes-And-Render-Modes: import { defineRoute, withStatus } from '@ultimat3/render';": 1,
  "Routes-And-Render-Modes: import { setRedirect } from '@ultimat3/http';": 1,
  'Routes-And-Render-Modes: meta: ({ post }) => ({ /* ... */ ld: ld.Article(post) })': 1,
  'SEO: export const config = defineRoute({': 2,
  "SEO: seo: { sitemap: { extra: ['/verificar', '/estado'], lastmod: 'git' } },": 1,
  'Scheduled-Tasks: // task (cron)': 1,
  'Scheduled-Tasks: export const rotateApiKeys = task({': 1,
  "Scheduled-Tasks: test('nightlyDigest enqueues one digest job per day', async ({ seed, clock }) => {": 1,
  'Scraping: const rent: CdpResolver = async ({ runId, egress, signal }) => {': 1,
  'Scraping: const waitForAnswer = eventPrompt({ timeout: 300_000 });': 1,
  'Scraping: expect: { minRows: 1, maxDrop: 0.5, window: 7 },': 1,
  'Scraping: export const dailyOrders = scrape({': 1,
  "Scraping: import { noWaitClock, resetScrapeClock, setScrapeClock } from '@ultimat3/scraping';": 1,
  'Scraping: recover: async ({ page, failure, attempt }) => { /* return true to re-run the body once */ }': 1,
  "Scraping: secrets: ['SHOP_PASSWORD'],": 1,
  "Static-Assets: import { setAssetResolver } from '@ultimat3/render';": 1,
  'Storage-And-Uploads: // apps/web/shared/storage.ts': 1,
  "Storage-And-Uploads: import { defineStorage, disk, localDriver, s3Driver, scopedKey } from '@ultimat3/storage';": 1,
  'Testing: // contract test — generated as a scaffold with the action': 1,
  'Testing: // job test — the step guarantee, not the happy path': 1,
  'Testing: // scripts/test-setup.ts': 2,
  "Testing: await expectedQueryLoop('one indexed lookup per searchable field', () => searchEachField(term));": 1,
  "Testing: const anAuthenticatedAction = sharedExamples<Denier>('an authenticated action', (subject) => {": 1,
  "Testing: const island = { build: buildIslands, root: join(import.meta.dir, '..', '..', '..') };": 1,
  "Testing: const row = await db.connections.insert({ label: 'primary', password: 'hunter2' });": 1,
  "Testing: const store = memoryLocalTx({ posts: { [id]: { id, title: 'before', pending: false } } });": 1,
  'Testing: export const summarizeEval = defineEval({': 1,
  "Testing: import { associate, defineFactory } from '@ultimat3/testing';": 1,
  "Testing: import { expect, renderRoute, renderView, unitTest } from '@ultimat3/testing';": 1,
  "Testing: test('the feed reads its authors once', async ({ statements }) => {": 1,
  "Testing: unitTest('a row deleted before the run is skipped, not failed', async ({ runJobs }) => {": 1,
  "Testing: unitTest('a session cookie resolves the member it was issued to', async () => {": 1,
  'The-Eight-Primitives: export const config = defineRoute({': 1,
  'The-Eight-Primitives: export const likePost = mutator({': 1,
  'The-Eight-Primitives: export const liveFeed = query({': 1,
  'The-Eight-Primitives: export const nightlyDigest = task({': 1,
  'The-Eight-Primitives: export const onboardOrg = job({': 1,
  'The-Eight-Primitives: export const publishPost = action({': 1,
  "The-Eight-Primitives: policy: can('post:publish', ({ input, actor }) => ownsPost(actor, input.postId))": 1,
  'Timezones-And-Dates: // task (cron)': 1,
  "Timezones-And-Dates: test('digest window respects the org zone', async ({ seed, clock }) => {": 1,
  'Tutorial-01-First-App: invariants: (c) => [': 1,
  'Tutorial-02-First-Feature: // apps/web/api/index.ts, in an app made with `x new --no-example` — importing it IS the boot': 1,
  "Tutorial-02-First-Feature: export const CreateTodoInput = todo.$view(['title', 'price']);": 1,
  'Tutorial-02-First-Feature: export const canTodoWrite = can<TodoScope>(': 1,
  "Tutorial-02-First-Feature: export const todo = entity('todos', {": 1,
  "Tutorial-02-First-Feature: export { todo } from '@myapp/web/app/todo/entity';": 1,
  'Tutorial-03-Auth-And-Admin: // apps/admin/app/admin/admin.ts': 1,
  "Tutorial-03-Auth-And-Admin: await register(auth, { email, password, orgId: org, roles: ['member'] });": 1,
  'Tutorial-03-Auth-And-Admin: export const noteAdminResource: AdminResourceOptions<AdminRow> = {': 1,
  "Tutorial-03-Auth-And-Admin: import { db, LIVE_RUN_STATUSES, runEvents, runs } from '@postly/db';": 1,
  "Tutorial-03-Auth-And-Admin: import { logout, signOutHeaders } from '@ultimat3/auth';": 1,
  'Tutorial-04-Jobs-And-Realtime: const first = await reindexTodo.enqueue({ id });': 1,
  'Tutorial-04-Jobs-And-Realtime: const source = await sourceFor(': 1,
  'Tutorial-04-Jobs-And-Realtime: export const dailyDigest = task({': 1,
  'Tutorial-04-Jobs-And-Realtime: export const reindexTodo = job({': 1,
  'Tutorial-04-Jobs-And-Realtime: export const todoList = query({': 1,
  'Tutorial-06-Growing-Up: // app.config.ts': 1,
  'Tutorial-06-Growing-Up: configureTelemetry({ exporter: otlpSpanExporter() });   // OTEL_EXPORTER_OTLP_ENDPOINT': 1,
  'UI-Components: <Link appearance="button" variant="secondary" size="sm" href="/posts/new">{t(\'posts.new\')}</Link>': 1,
  'Upgrading: // before — answered ALLOWED, and admitsAnonymous() agreed, so http did not 401 first': 1,
  'Upgrading: // before — compiles, and is circular: the factory that BUILDS ctx.posts': 1,
  "Upgrading: case 'missing-check':": 1,
  'Upgrading: configureLifecycle({ deadlineMs: 600_000 });   // and terminationGracePeriodSeconds >= 600': 1,
  'Upgrading: generateServiceWorker(routes, config, buildId);   // from @ultimat3/pwa': 1,
  'Upgrading: mcpHttpRoute({ server, resolveToken, rateLimitStore: postgresRateLimitStore({ executor }) });': 1,
  'Upgrading: mcpHttpRoute({ server, resolveToken, rateLimits: { read: 600, write: 60 } });': 1,
  'Upgrading: registerErrorStatus({ X_PAYMENTS_UNREACHABLE: 502 });   // from @ultimat3/http, once at boot': 1,
  'Upgrading: setJobDriver(createPgDriver({ executor }))   // production': 1,
};
