-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

alter table "comments" add constraint "comments_author_id_fkey" FOREIGN KEY (author_id) REFERENCES members(id) ON DELETE RESTRICT;

alter table "comments" add constraint "comments_org_id_fkey" FOREIGN KEY (org_id) REFERENCES orgs(id) ON DELETE CASCADE;

alter table "comments" add constraint "comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;
