-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

alter table "post_reviews" add constraint "post_reviews_org_id_fkey" FOREIGN KEY (org_id) REFERENCES orgs(id) ON DELETE CASCADE;

alter table "post_reviews" add constraint "post_reviews_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;

alter table "post_reviews" add constraint "post_reviews_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES members(id) ON DELETE CASCADE;
