-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "comments" (
  "id" uuid not null,
  "org_id" uuid not null,
  "post_id" uuid not null,
  "author_id" uuid not null,
  "body" text not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "comments_pkey" PRIMARY KEY (id),
  constraint "comments_body_check" CHECK ((char_length(body) <= 2000)),
  constraint "comments_comment_body_present_check" CHECK ((char_length(btrim(body)) >= 1))
);
