-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "likes" (
  "org_id" uuid not null,
  "post_id" uuid not null,
  "member_id" uuid not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "likes_pkey" PRIMARY KEY (post_id, member_id)
);

alter table "likes" replica identity full;
