-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "orgs" (
  "id" uuid not null,
  "slug" text not null,
  "name" text not null,
  "plan_code" text default 'free'::plan_code not null,
  "billing_currency" text default 'USD'::billing_currency not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "orgs_pkey" PRIMARY KEY (id),
  constraint "orgs_slug_key" UNIQUE (slug),
  constraint "orgs_billing_currency_check" CHECK ((billing_currency = ANY (ARRAY['USD'::text, 'EUR'::text]))),
  constraint "orgs_name_check" CHECK ((char_length(name) <= 80)),
  constraint "orgs_org_name_present_check" CHECK ((char_length(btrim(name)) >= 1)),
  constraint "orgs_org_slug_shape_check" CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)),
  constraint "orgs_plan_code_check" CHECK ((plan_code = ANY (ARRAY['free'::text, 'team'::text, 'business'::text]))),
  constraint "orgs_slug_check" CHECK ((char_length(slug) <= 80))
);
