-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "post_reviews" (
  "post_id" uuid not null,
  "org_id" uuid not null,
  "verdict" text not null,
  "notes" text not null,
  "reviewed_by" uuid not null,
  "reviewed_at" timestamp with time zone default now() not null,
  constraint "post_reviews_pkey" PRIMARY KEY (org_id, post_id),
  constraint "post_reviews_notes_check" CHECK ((char_length(notes) <= 600)),
  constraint "post_reviews_verdict_check" CHECK ((verdict = ANY (ARRAY['ready'::text, 'revise'::text])))
);
