-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "posts" (
  "id" uuid not null,
  "org_id" uuid not null,
  "author_id" uuid not null,
  "slug" text not null,
  "title" text not null,
  "excerpt" text not null,
  "body" text not null,
  "cover_url" text,
  "status" text default 'draft'::post_status not null,
  "like_count" integer default 0 not null,
  "published_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "posts_pkey" PRIMARY KEY (id),
  constraint "posts_cover_url_check" CHECK ((cover_url ~ '^https?://'::text)),
  constraint "posts_excerpt_check" CHECK ((char_length(excerpt) <= 200)),
  constraint "posts_post_like_count_non_negative_check" CHECK ((like_count >= 0)),
  constraint "posts_post_publish_coherent_check" CHECK (((status = 'published'::text) = (published_at IS NOT NULL))),
  constraint "posts_post_slug_shape_check" CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)),
  constraint "posts_slug_check" CHECK ((char_length(slug) <= 80)),
  constraint "posts_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'published'::text]))),
  constraint "posts_title_check" CHECK ((char_length(title) <= 120))
);

alter table "posts" replica identity full;
