-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "run_events" (
  "id" uuid default gen_random_uuid() not null,
  "org_id" uuid not null,
  "run_id" uuid not null,
  "seq" integer not null,
  "kind" text not null,
  "at" timestamp with time zone default now() not null,
  "message" text not null,
  "prompt" integer,
  "usage" jsonb,
  constraint "run_events_pkey" PRIMARY KEY (id),
  constraint "run_events_kind_check" CHECK ((kind = ANY (ARRAY['prompt'::text, 'answered'::text, 'navigated'::text, 'extracted'::text, 'done'::text, 'failed'::text, 'usage'::text]))),
  constraint "run_events_message_check" CHECK ((char_length(message) <= 200)),
  constraint "run_events_run_event_seq_from_one_check" CHECK ((seq >= 1))
);

alter table "run_events" replica identity full;
