-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "runs" (
  "id" uuid default gen_random_uuid() not null,
  "org_id" uuid not null,
  "connection_id" uuid not null,
  "job_id" text not null,
  "status" text not null,
  "code" text,
  "started_at" timestamp with time zone default now() not null,
  constraint "runs_pkey" PRIMARY KEY (id),
  constraint "runs_code_check" CHECK ((char_length(code) <= 64)),
  constraint "runs_job_id_check" CHECK ((char_length(job_id) <= 64)),
  constraint "runs_status_check" CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'done'::text, 'failed'::text])))
);
