-- generated by `x db gen` from the migrations; never edited by hand (X_SCHEMA_DUMP_DRIFT)

create table "webhook_deliveries" (
  "id" uuid default gen_random_uuid() not null,
  "org_id" uuid not null,
  "endpoint_id" uuid not null,
  "webhook" text not null,
  "event_id" text not null,
  "topic" text not null,
  "attempt" integer not null,
  "ok" boolean not null,
  "status" integer,
  "duration_ms" integer not null,
  "error" text,
  "consecutive_failures" integer not null,
  "at" timestamp with time zone not null,
  constraint "webhook_deliveries_pkey" PRIMARY KEY (id),
  constraint "webhook_deliveries_error_check" CHECK ((char_length(error) <= 500)),
  constraint "webhook_deliveries_event_id_check" CHECK ((char_length(event_id) <= 128)),
  constraint "webhook_deliveries_topic_check" CHECK ((char_length(topic) <= 80)),
  constraint "webhook_deliveries_webhook_check" CHECK ((char_length(webhook) <= 80))
);
