import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { assertAgentsMd, checkAgentsMd } from './agents-md.ts';

let dir = '';

beforeAll(async () => {
  dir = await mkdtemp(join(tmpdir(), 'ultimate-agents-md-'));
});

afterAll(async () => {
  await rm(dir, { recursive: true, force: true });
});

const write = async (name: string, text: string): Promise<string> => {
  const path = join(dir, name);
  await Bun.write(path, text);
  return path;
};

describe('AGENTS.md is validated, never generated', () => {
  test('a missing file fails with a fix that says to write one by hand', async () => {
    const path = join(dir, 'absent.md');
    let thrown: { code?: unknown; fix?: unknown } | undefined;
    try {
      await assertAgentsMd({ path });
    } catch (error) {
      thrown = error as { code?: unknown; fix?: unknown };
    }
    expect(thrown?.code).toBe('X_AGENTS_MD_MISSING');
    // Research says generated context files lower task success — so the fix is "write one",
    // never "run x agents-md". There is deliberately no generator to point at.
    expect(String(thrown?.fix)).toContain('by hand');
    expect(String(thrown?.fix)).not.toContain('x agents');
  });

  test('a file over budget fails and names both numbers', async () => {
    const path = await write('big.md', 'x'.repeat(500));
    let thrown: { code?: unknown; cause?: unknown } | undefined;
    try {
      await assertAgentsMd({ path, maxBytes: 100 });
    } catch (error) {
      thrown = error as { code?: unknown; cause?: unknown };
    }
    expect(thrown?.code).toBe('X_AGENTS_MD_TOO_LARGE');
    expect(String(thrown?.cause)).toContain('500B');
    expect(String(thrown?.cause)).toContain('100B');
  });

  test('a short hand-written file passes', async () => {
    const path = await write('ok.md', '# acme\n\nBun + Postgres. `bun run dev`. Never edit db/.\n');
    const check = await assertAgentsMd({ path });
    expect(check.ok).toBe(true);
    expect(check.warnings).toEqual([]);
  });

  test('duplicated generated facts are warned about, not failed', async () => {
    const path = await write(
      'warn.md',
      ['# acme', '', '| column | type |', '| --- | --- |', '| id | uuid |', ''].join('\n'),
    );
    const check = await checkAgentsMd({ path });
    // A warning, not an error: it is a judgement call, and only a human can make it.
    expect(check.ok).toBe(true);
    expect(check.warnings.join(' ')).toContain('x.manifest.json');
  });

  test('a file claiming to be generated is warned about', async () => {
    const path = await write('gen.md', '<!-- Generated by tooling. DO NOT EDIT -->\n# acme\n');
    const check = await checkAgentsMd({ path });
    expect(check.warnings.join(' ')).toContain('human-authored');
  });
});
