// AGENTS.md validation. Read-only, deliberately narrow.
//
// WHY THIS DOES NOT GENERATE PROSE
// --------------------------------
// The obvious feature request is "generate AGENTS.md from the code". We refuse, on evidence:
// LLM-generated context files measurably REDUCE task success and increase the number of
// steps an agent takes. The generated prose reads plausibly, drifts from reality the moment
// anything changes, and — worst of all — an agent trusts it over the code.
//
// So the split is: FACTS ARE GENERATED, CONVENTIONS ARE HUMAN-AUTHORED. `x.manifest.json`
// carries everything derivable from code and is regenerated on every build. `AGENTS.md`
// carries what a human knows and code cannot express — why this queue is separate, which
// service is load-bearing, what not to touch — and stays short enough to be read every time.
//
// This module therefore checks exactly two things: that the file exists, and that it has not
// grown into a document nobody reads. It never writes.

import { AgentsMdMissingError, AgentsMdTooLargeError } from './errors.ts';

export const AGENTS_MD_FILENAME = 'AGENTS.md';

/**
 * Default budget, in bytes. Roughly 3k tokens — long enough for stack, commands, conventions,
 * and hard-won gotchas; short enough that an agent reads all of it rather than skimming.
 */
export const AGENTS_MD_MAX_BYTES = 12_000;

export interface AgentsMdCheck {
  readonly path: string;
  readonly exists: boolean;
  readonly bytes: number;
  readonly maxBytes: number;
  readonly ok: boolean;
  /** Non-fatal observations, surfaced by `x verify --json` for a human to judge. */
  readonly warnings: readonly string[];
}

export interface CheckAgentsMdInput {
  readonly path?: string;
  readonly maxBytes?: number;
}

/** Inspect without throwing — `x verify --json` reports, `assertAgentsMd` enforces. */
export async function checkAgentsMd(input: CheckAgentsMdInput = {}): Promise<AgentsMdCheck> {
  const path = input.path ?? `./${AGENTS_MD_FILENAME}`;
  const maxBytes = input.maxBytes ?? AGENTS_MD_MAX_BYTES;
  const file = Bun.file(path);

  if (!(await file.exists())) {
    return { path, exists: false, bytes: 0, maxBytes, ok: false, warnings: [] };
  }
  const text = await file.text();
  const bytes = Buffer.byteLength(text, 'utf8');
  return {
    path,
    exists: true,
    bytes,
    maxBytes,
    ok: bytes <= maxBytes,
    warnings: warningsFor(text),
  };
}

/** The `x verify` gate. Throws `X_AGENTS_MD_*`; never repairs the file. */
export async function assertAgentsMd(input: CheckAgentsMdInput = {}): Promise<AgentsMdCheck> {
  const check = await checkAgentsMd(input);
  if (!check.exists) throw new AgentsMdMissingError({ path: check.path });
  if (check.bytes > check.maxBytes) {
    throw new AgentsMdTooLargeError({
      path: check.path,
      bytes: check.bytes,
      maxBytes: check.maxBytes,
    });
  }
  return check;
}

/**
 * Warn when the file has started duplicating generated facts. Duplication is how a context
 * file goes stale: the copy and the source drift, and the agent believes the copy.
 */
function warningsFor(text: string): readonly string[] {
  const warnings: string[] = [];
  if (/^\s*\|.*\|\s*$/m.test(text) && /\b(column|entity|route|endpoint)\b/i.test(text)) {
    warnings.push('looks like it tabulates schema or route facts; those live in x.manifest.json');
  }
  if (text.split('\n').length > 200) {
    warnings.push('over 200 lines; a context file that long is skimmed, not read');
  }
  if (/generated by|do not edit/i.test(text)) {
    warnings.push('claims to be generated; AGENTS.md is human-authored by design');
  }
  return warnings;
}
